### ISSUE TITLE
 Full Request Support

### ISSUE THREAD

**Issue by Dargmuesli** [thelinmichael/spotify-web-api-java#102]
Support the whole [Web API Endpoint Reference](https://developer.spotify.com/web-api/endpoint-reference/).

**Comment by Loki-Afro** [comment]
is there a specific branch to try out the new features? ;)

**Comment by Dargmuesli** [comment]
Currently not. I'm changing so many parts of this project that branch `v2` and all related branches are in a heavily WIP state. Let me explain it like that: I'm not adding individual features one by one. I take care of all at once and rework the whole semantic. For example, the utilprotos are being removed completely and replaced by stock URI functionality. Class layouts change completely.

With this many unfinished sections I cannot recommend a branch to test the new features, sorry.

**Comment by Dargmuesli** [comment]
Merged branch `v2_requests` in 9899e12d3f8290f0096702389efd8d4d92a53401.

**Comment by Dargmuesli** [comment]
Now I've updated the auth requests too and sorted classes.

@Loki-Afro have a look at https://dargmuesli.github.io/spotify-web-api-java/ where I've currently made a build of the current v2 documentation available if you want to have a preview of this.

**Comment by Loki-Afro** [comment]
@Dargmuesli thanks, but another potential stupid question:

Is there anywere a snippet of code that show how to use the refresh token now? => What happened to `refreshAccessToken` in `Api` ?

**Comment by Dargmuesli** [comment]
Yes, I've only implemented the changes required with some side effects like `refreshAccessToken` being temporarily removed. I've not started testing with use cases like you did and I don't expect those to work yet. Hence, your additions/corrections are most likely completely correct. I just wanted to make the current state of changes visible to you, not encourage to build on them ;)
But thanks for your suggestions though, they'll be definitly helpful for work on usability testing!

I'll give you an update when this stage is reached.

**Comment by Loki-Afro** [comment]
I will put some commits and when my basic use case is done I'll create some pull requests if still necessary if you are fine with that ;)

**Comment by Dargmuesli** [comment]
Yes, you surely can do that if still necessary. But first give me some time to work on this myself, so that I keep an overview ;) This will still take a little time and will be one of the last steps before publication of v2. Stay tuned for the next week.
I wish you a happy new year!

**Comment by Loki-Afro** [comment]
I made a PR for 1. and 2. https://github.com/thelinmichael/spotify-web-api-java/pull/110

But I have to add point :D 

5. It is currently only possible to create opst requests which are url encoded, this logic was present in the master but is not archiveable in the same way. 

This affects creating a playlist and addting tracks to a playlist. Should be a trivial change 


I have to say you should keep AbstractRequests and these Builders clean of these apache component stuff to. Often these apache libs are not welcome in older projects since they can break a lot of dependencies, so keeping these stuff out would be desireable expect of course `SpotifyHttpManager`

**Comment by Dargmuesli** [comment]
Thanks for the ideas, but please read my previous comment again. Regarding force-pushs: I only use those after agreement on those affected, like assignees. This time, they were informed and agreed via email and IM. This should be no problem as long as everyone interested in contributing to this project leaves a note here, as generally suggested. I'll add a note about this in the coming days to clarify it even more.

**Comment by Dargmuesli** [comment]
@Loki-Afro 

1. is fixed now
2. I want to let more thoughts go into this on my side
3. Are you referring to your quickfix in point 2?
4. Please submit a PR for that
5. Can you please explain a little more what you mean exactly?

Also: why should this project's dependencies interfere with older projects? I haven't understood this yet. But I'll think of alternatives nevertheless.

If you are sure about a certain problem, please open a separate issue for it in the future.

**Comment by Dargmuesli** [comment]
I've removed both guava (090f6ef1831220dfe66cf82098a6d074fd2cee9c) and commons-codec (a0a2ccc9d92e97776e0bf2bef0c769cd58e05e15) dependencies. Could lead to errors though.

**Comment by Dargmuesli** [comment]
Point 2 and 4 are fixed now, without any hax:
- d17513bbda111427bc48efab74c71f186a82beca
- f077e5b10b794556cd5ca1b7a37fa72f1a267d5d

Please explain what you mean with point 3 and 5 to me @Loki-Afro.

**Comment by Loki-Afro** [comment]
3. calling printStacktrace in a lib is not a good idea without using any logger
5. There are POST requests which have to be url encoded (like you submit a form in a HTML way) and there are POST requests where you simply send a json, those should have the contentType application/json  SpotifyHttpManager did only handle the url encoded one, can't check the current code now

**Comment by Dargmuesli** [comment]
3. Good point. A logger is available since 32780450a3b62ea6a24c5e65b86e0059c38419d2. I'll take care of this!
4. The reference states:

> Content-Type | Required if URIs are passed in the request body, otherwise ignored. The content type of the request body: application/json
> -- | --

Currently (v2) all requests have the "content-type = application/json" header. Hence, this should be fine.

**Comment by Loki-Afro** [comment]
4. this is not true since the authentication mechanism uses url encoded requests, try it out...

**Comment by Dargmuesli** [comment]
Ok, you are referring to [Authorization Code Flow: 2.](https://beta.developer.spotify.com/documentation/general/guides/authorization-guide/#2-have-your-application-request-refresh-and-access-tokens-spotify-returns-access-and-refresh-tokens):

> The body of this POST request must contain the following parameters encoded in ´application/x-www-form-urlencoded as defined in the OAuth 2.0 specification

I'm working on a fix.

**Comment by Dargmuesli** [comment]
Fixed (f6ed9003c8cf5d9efe7d6474b254b0d0e3b0a507).

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
