### ISSUE TITLE
No Naming Convention

### ISSUE THREAD

**Issue by Dargmuesli** [thelinmichael/spotify-web-api-java#105]
There is no clear naming convention regarding the request classes. Come up with one while writing all new request classes!

**Comment by Dargmuesli** [comment]
Neither fixtures follow a naming convention. #103

**Comment by Dargmuesli** [comment]
In branch `v2` request are now sorted and follow a simple naming convention in comparison to the [Web API Reference](https://beta.developer.spotify.com/documentation/web-api/reference/).

Fixtures will be dealt with in #103.

**Comment by Dargmuesli** [comment]
The API reference changed the request names. When @c-schuhmann's work on documentation is finished, the names will be updated.

**Comment by c-schuhmann** [comment]
The school is a little bit stressful atm, but in my free hours where I will definitely work on it :) I complete all other model objects (only the authentication ones are remaining) and continue with the exceptions. After that I work on the requests.

**Comment by Dargmuesli** [comment]
No problem at all. Until #65 is not resolved, it doesn't really matter how fast development goes. Take all time you need. 
But if you aren't working on requests yet, I could already change their titles.

**Comment by c-schuhmann** [comment]
You can already change the titles if you want :)
