### ISSUE TITLE
Missing Tests

### ISSUE THREAD

**Issue by Dargmuesli** [thelinmichael/spotify-web-api-java#107]
Tests are currently in a state that we cannot keep. There needs to be a unified pattern and full test coverage!

**Comment by PedramPejman** [comment]
Hi @Dargmuesli is this blocking v2 release? Any idea when the release will be pushed out? Thanks so much!

**Comment by Dargmuesli** [comment]
Yes, I'd like to keep it that way. But that shouldn't be the main issue. I honestly don't feel any time pressure regarding the tedious task of implementing all tests as #65 isn't resolved. @thelinmichael has to grant me deploy rights and I haven't heard from him in a long time. Have a look at this issue if you want to see a way to use the current master branch as Maven dependency.

**Comment by Dargmuesli** [comment]
Tests were added in:
- General (2ce4f0382b1a381c1da8db79fffbaa43c8a80ef7)
- Authorization (2aff5f81e78d7702a3fc2a902087c44510400f9f)
- Albums (07b9c92d2ecbb894ea4a6befe22e2c5cafd5f703)
- Artists (cf03d1e89979cb219f86be3c6df8759aa73b4b53)
- Browse (87945c08da42684b739f0e6adf2b9e7a25085ed9)
- Follow (4875a509c99eb11b366ea515a1ae477cd365cf7d)
- Library (728aa02e6b9d152c9592946b04f461819d9cdf3c)
- Personalization (b93beb15e6950d8db2faeaa77463100421cfd752)
- Player (f5cb35c99d773aed60267b7404d252db1411df5f, 361cb223d76c34582baabc853035423c645167de)
- Playlists (db465ed9694e73cdb9522b5377da099270017af2)
- Search (5a68ea43bd691783055be707b3168709c23f440e)
- Track (36b5755b5ad41ac0dbf95001a19bb8c7d467a2cc)
- User (b51ed2302ff6db1d6eb9f1778f18f41b51199f66)

The testing methods require some additional thoughts though. I'll keep this issue open until then.
Btw: the release of v2 moves significantly closer as Mr. Thelin said he'd take care of Maven deploy rights in the course of the day.

**Comment by Dargmuesli** [comment]
Test naming was altered in 316fdb88778bb1704547bb303e45f4e02ce2d6bd and ApiTest functions were rewritten per request test in 1423d88e6334eeefffb5c3aad47b8a59c0514633.

**Comment by Dargmuesli** [comment]
@PedramPejman Version 2.0.0-RC1 of spotify-web-api-java was just released.
