### ISSUE TITLE
New README(s)

### ISSUE THREAD

**Issue by Dargmuesli** [thelinmichael/spotify-web-api-java#109]
The current README is very long. Let's clean it up a little.

**Comment by Dargmuesli** [comment]
We need a place for this project's Javadoc (#95). Maybe GitHub Pages? This could make the lengthy, individual explanations on how to use the API methods unnecessary.

**Comment by c-schuhmann** [comment]
I like the idea with GitHub Pages! Until now, the documentation was only distributed as a jar file through Maven Central, but with GitHub Pages we could make it easier to access. Either we include the Javadoc directly into the projects directory or create a new repository only containing the Javadoc. Otherwise we could host it ourselves or integrate it into a GitHub User Page. I would create a new repository to separate it a little bit.

**Comment by Dargmuesli** [comment]
I've tried out publishing a GitHub Pages page for the documentation https://dargmuesli.github.io/spotify-web-api-java and it works out quite nicely. I'd say keeping the Javadoc in a `docs/` folder is the most convenient way I currently see. This way we keep everything in one package and under Michael Thelins umbrella.
On the other hand is enabling the GitHub Pages feature a thing only Michael Thelin can do. I'll ping him about this and maybe get Maven deploy rights at the same time (#65).

**Comment by Dargmuesli** [comment]
The link above now points to a build of the `v2` branch documentation (not `v2_documentation`) inside a gh-pages branch. That's just for showing the changes that are coming in v2.

Also, I've almost finished working on requests, @c-schuhmann. Go ahead with documentation :)
I'll try to rebase the documentation branch on v2.

**Comment by Dargmuesli** [comment]
Rebased. Link now points to `v2_documentation`'s documentation ;)

**Comment by Dargmuesli** [comment]
I've added contribution guidelines file (c765f5e162a37527e701e1f854f445179f1b2e41) and a "code overview" section in the README (8b13b083c82992c07f4150f56416ef8c77f9d7d1).

**Comment by Dargmuesli** [comment]
Up-to-date example classes for all requests were added in e4465213303ee47dc94fe3a76ef31fa0f8a97220.

**Comment by Dargmuesli** [comment]
The README was updated in 28e972f4460302c8a7e618b528780d2be22408d1.
