### ISSUE TITLE
3 years since the last release?

### ISSUE THREAD

**Issue by seantcanavan** [thelinmichael/spotify-web-api-java#115]
Maven Repository shows that 1.5 was released on January 2015. It's now January 2018. Is there any way to get an updated release with the latest fixes and updates?

**Comment by Dargmuesli** [comment]
v2 is in the work, but currently there's no way for me to publish a build to Maven. See #65.
However, as @napstr suggested, you can use [jitpack](https://jitpack.io/) to test out v2, work with the current master branch or the version of a specific commit.

**Comment by Dargmuesli** [comment]
I'll put a reference to this issue into the README.

**Comment by seantcanavan** [comment]
It's mostly my bad - I didn't make it all the way down the list of issues. I did make it all the way down the README though :)

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 of spotify-web-api-java was just released.
