### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by imdutch21** [thelinmichael/spotify-web-api-java#120]
I seem to be having a problem with using the api. I've made a little program for testing the capabilities of the api, but after trying to build a new instance of the api
`Api api = Api.builder().accessToken(oauthToken).clientId(CLIENT_ID).redirectURI(UIR).build();`
the following error is given: 
`java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/conn/PoolingHttpClientConnectionManager;`

Full error log: https://pastebin.com/N9ihEaJt 

I've looked online for solutions, but I can't seem to find any fixes that work. Has anyone got any clue for how to fix this?

Dependencies:

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    compile 'com.spotify.sdk:spotify-player-24-noconnect-2.20b@aar'
    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.spotify.android:auth:1.0.0-alpha'
    testCompile 'junit:junit:4.12'

    compile('se.michaelthelin.spotify:spotify-web-api-java:1.7.3') {
        exclude group: "commons-beanutils", module: "commons-beanutils"

    }
    compile 'commons-beanutils:commons-beanutils:20030211.134440'
}
```

**Comment by Dargmuesli** [comment]
I'll look into this. Are you using Android? You may use [kaaes/spotify-web-api-android] (https://github.com/kaaes/spotify-web-api-android) instead.

**Comment by imdutch21** [comment]
Oh yes I am. I've tried that api as well, but I was having a different issue with that one. I actually thought this one was for android as well. If the issue has no easy fix, I'll look into kaaes' wrapper again

**Comment by imdutch21** [comment]
Sure
I'm using android studio 2.3, but I think that shouldn't matter
Main: https://pastebin.com/LRHB0N7t
Main XML: https://pastebin.com/Nwa1iJyT
Gradle: https://pastebin.com/0aRv9S6K

For the virtual device I use the Pixel XL with api 24
If you need anything else, I'm happy to help

**Comment by imdutch21** [comment]
Actually I forgot to mention I'm also using Spotify's android sdk for authentication

**Comment by Dargmuesli** [comment]
Have you tried using the new version 2.0.0-RC1 of this project? Does the same problem still occur?

**Comment by Dargmuesli** [comment]
Ok, I've narrowed down the issue. Sadly, this cannot be fixed. Other people call this issue

> [a colossal cock-up](https://stackoverflow.com/a/4818714/4682621)

on which I must fully agree.

It boils down to Android's included, but very very outdated and thus incompatible version of the httpclient dependency this project relies on too. [There are efforts](https://github.com/smarek/httpclient-android/wiki/Project-Introduction) making usage of the current dependency versions possible, but this would mean that we'd need to include a different package and not the original. As far as I can see this would make no sense for this project as there are others (like kaaes') that are specifically made for Android.

Further explanation: [HttpClient for Android](https://hc.apache.org/httpcomponents-client-4.5.x/android-port.html)

Sorry for the inconvenience, I'll change the README accordingly. Good luck with your project!

**Comment by imdutch21** [comment]
Okay I understand! Thank you for all your effort and I will try to make the best out of my project!
