### ISSUE TITLE
Encoding of special characters not working on artist search

### ISSUE THREAD

**Issue by wbijen** [thelinmichael/spotify-web-api-java#121]
First of all, great work! This is one nice wrapper!

I've upgraded the wrapper from 1.5.0 to the latest version and I've encountered a new bug. 
When searching on the api with the searchArtists(#name).market(#market) I get an IllegalArgumentException. 

For example when searching for the artist "Brand New Wayo" :  

java.lang.IllegalArgumentException: Illegal character in query at index 57: https://api.spotify.com:443/v1/search?type=artist&q=Brand New Wayo&market=nl

It's kind of obvious what is happening, the space char isn't encoded to HTML entities.

**Comment by Dargmuesli** [comment]
Should be fixed in 0023eddf33f6dda545aa4b6ea958fd0e4809cda8. But I suggest that you check out v2.0.0 which will be released this weekend.

**Comment by wbijen** [comment]
v2.0.0 looks good! Definitely going to switch

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 of spotify-web-api-java was just released.
