### ISSUE TITLE
Extending of Models not allowed. Constructor is private.

### ISSUE THREAD

**Issue by wbijen** [thelinmichael/spotify-web-api-java#124]
I would like to extend the model Artist because it's preferable in my business logic.

Currently there is no way to extend the artist object because the constructor access is private. I presume this is done because of the Builder.

But this creates a problem for me. Is there any way to get this working?

I'm on version 2.0.0-RC1

**Comment by Dargmuesli** [comment]
Model objects are not meant to be extendable, because they follow a specification.
- What exactly is the problem you are speaking of?
- What exactly do you want to change in you extending class?
- What prevents you from writing your own custom class?

**Comment by Dargmuesli** [comment]
Maybe an option would be to make the constructors public and deprecated. But I'd first like to know answers to the questions above.

**Comment by Dargmuesli** [comment]
Putting this on hold until someone gives a conrete example.
