### ISSUE TITLE
Inconsistency with usages of assert in SpotifyApi class

### ISSUE THREAD

**Issue by kschow** [thelinmichael/spotify-web-api-java#125]
A couple things, I noticed that this function in the SpotifyApi class doesn't have asserts in it. It probably should given the other functions like it: 
```Java
public AuthorizationCodeUriRequest.Builder authorizationCodeUri(String client_id, URI redirect_uri) {
    return new AuthorizationCodeUriRequest.Builder()
            .setDefaults(httpManager, scheme, host, port)
            .client_id(client_id)
            .response_type("code")
            .redirect_uri(redirect_uri);
  }
```
If it were to match everything else, it would need these three lines:
`assert (client_id != null);`
`assert (!client_id.equals(""));`
`assert (redirect_uri != null);`

A bit more generally though, what's the reasoning behind putting these asserts in this class (SpotifyApi) as well as all of the individual request classes? The logic is duplicated which makes managing it more complicated, specifically needing to change both of them if something changes, like id limits.

I also noticed that some of the asserts here don't match the ones in the request classes. An example being:`assert (1 <= ids.length && ids.length <= 20);` vs `assert (ids.split(",").length <= 20);` for the GetSeveralAlbumsRequest. The SpotifyApi one checks both a lower limit and an upper limit while the GetSeveralAlbumsRequest one only checks an upper limit.

Slightly separately, does it make sense to make the various limits publicly available? Namely something like `public static int MAXIMUM_IDS = 20;` in the GetSeveralAlbumsRequest class that can be used in both places (SpotifyApi/GetSeveralAlbumsRequest) as well as for any consumers of this API.

**Comment by Dargmuesli** [comment]
Yes, the usage of asserts in the API class is arguably unnecessary. I once had a strategy putting them into it, but I cannot remember why. When I look at it now, I cannot come up with something that would prevent it from being removed. Do you want to submit a pull request for that?

**Comment by kschow** [comment]
Submitted pull request #127 for this issue.

**Comment by Dargmuesli** [comment]
Please keep in mind that you can add [syntax-highlighted code blocks in GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/).
