### ISSUE TITLE
Throw exception when a error occurs 

### ISSUE THREAD

**Issue by kaanmijo** [thelinmichael/spotify-web-api-java#128]
Hi there,

I'm currently developing a application in Java using this library. I'm currently experiencing a problem with catching errors, and I hope someone could help me with it.

The problem is as follows: when a request to the API is made and something went wrong (wrong token, expired token etc..), an error is logged to the console. However, no error is actually thrown by the library.

Is it possible for me to check if a request succeeded or failed without checking the logs?

Thanks!

**Comment by Dargmuesli** [comment]
Could you please show me a snippet of your code that implements a request that doesn't throw an error?

**Comment by kaanmijo** [comment]
It's not a snippet of code. The only way to detect if a token is expired, for example, is to check if the response is "null" and there is a message present in the logging that says "token expired".

**Comment by Dargmuesli** [comment]
Please show me the full code in which you make that request.

**Comment by kaanmijo** [comment]
```
 public ApiReturnModel getPlaylist(@RequestHeader("accesstoken") String accessToken) {
        try {
            LOGGER.info("Get playlist list by accesstoken: " + accessToken);
            SpotifyApi spotifyApi = new SpotifyApi.Builder()
                    .setAccessToken(accessToken)
                    .build();

            final GetListOfCurrentUsersPlaylistsRequest getListOfCurrentUsersPlaylistsRequest = spotifyApi
                    .getListOfCurrentUsersPlaylists()
                    .build();
            final Future<Paging<PlaylistSimplified>> pagingFuture = getListOfCurrentUsersPlaylistsRequest.executeAsync();
            Paging<PlaylistSimplified> playlistData = pagingFuture.get();
            return new ApiReturnModel<Paging<PlaylistSimplified>>(true, accessToken, new Date(), playlistData);
        } catch (InterruptedException | ExecutionException e) {
            LOGGER.error("Cannot find playlists.", e);
            return null;
        }
    }
```

**Comment by Dargmuesli** [comment]
So your question refers to asynchronous requests, am I right? These should throw `SpotifyWebApiException`s too. You should be able to access them via `e.getCause()`.

**Comment by Dargmuesli** [comment]
But you're right, I've found the lines that are causing this behavior. I'll fix this and update the examples.
