### ISSUE TITLE
Enum ProductType does not include BASIC-DESKTOP

### ISSUE THREAD

**Issue by Bart1909** [thelinmichael/spotify-web-api-java#130]
There seems to be an additional Product-Type "BASIC-DESKTOP" which is not included in the enum ProductType.

Sample-Data
`{
  "country" : "DE",
  "display_name" : "Test User",
  "external_urls" : {
    "spotify" : "https://open.spotify.com/user/1234"
  },
  "followers" : {
    "href" : null,
    "total" : 3
  },
  "href" : "https://api.spotify.com/v1/users/1234",
  "id" : "1234",
  "images" : [ {
    "height" : null,
    "url" : "https://scontent.xx.fbcdn.net/v/13",
    "width" : null
  } ],
  "product" : "basic-desktop",
  "type" : "user",
  "uri" : "spotify:user:1234"
}`

**Comment by Dargmuesli** [comment]
What request returned this result?

**Comment by Bart1909** [comment]
While getting the current Users Profile: GetCurrentUsersProfileExample

**Comment by Dargmuesli** [comment]
Ok, what kind of product are you using? What do you think "basic-desktop" stands for?
(does it really contain a dash or an underscore?)

**Comment by Bart1909** [comment]
This is not my Account. 

The example is original, I have only changed the personal information.

**Comment by Bart1909** [comment]
Hi @Dargmuesli,

the Value returned from Spotify is "basic-desktop" with a dash. But in the enum the value is BASIC_DESKTOP with an underscore. So this is not working yet.
If you want, contact me privately and I will give you an accessToken from the user-account in my example for testing purpose.

**Comment by Dargmuesli** [comment]
Fixed for all enums.
