### ISSUE TITLE
AuthorizationCodeCredentials doesn't return new refreshToken, is always null

### ISSUE THREAD

**Issue by kaanmijo** [thelinmichael/spotify-web-api-java#131]
Hi,

I'm currently using this code to refresh a users access and refresh token:

```Java
SpotifyApi spotifyApi = new SpotifyApi.Builder()
                    .setClientId(properties.getClientId())
                    .setClientSecret(properties.getClientSecret())
                    .setRefreshToken(spotifyToken.getRefreshToken())
                    .build();

AuthorizationCodeRefreshRequest authorizationCodeRefreshRequest = spotifyApi.authorizationCodeRefresh().build();
Future<AuthorizationCodeCredentials> authorizationCodeCredentialsFuture = authorizationCodeRefreshRequest.executeAsync();

final AuthorizationCodeCredentials authorizationCodeCredentials = authorizationCodeCredentialsFuture.get();
spotifyToken.setAccessToken(authorizationCodeCredentials.getAccessToken());
spotifyToken.setRefreshToken(authorizationCodeCredentials.getRefreshToken());
```

When executing the code above, this is the response I get:

![image](https://user-images.githubusercontent.com/4430874/36061474-0c01aedc-0e5b-11e8-9321-8d61cd78529f.png)

The `spotifyToken` shown is the old data I use to make a refresh request. As you can see in `authorizationCodeCredentials`, the accessToken is refreshed. However, the refreshToken is always null. 

This isn't just a problem with async requests, it also exists with normal requests.

**Comment by Dargmuesli** [comment]
This is correct behavior. Just keep using your refresh token for all access token refresh requests. I'll update the examples and remove the incorrect misleading line that sets a new refresh token.
