### ISSUE TITLE
Help with Authorization

### ISSUE THREAD

**Issue by plimplom** [thelinmichael/spotify-web-api-java#137]
After alot of trying I think it might help if I ask this here.

How do I automate the authorization progress, if that is even possible. I looked at the examples, but my issue is that I want to have the access token generated at start of the program.
Currently I have to paste the generated link into my browser, then copy the return code into another piece of code to get the access Token generated.

Thanks for the help in advance
-plimplom

**Comment by Dargmuesli** [comment]
That is not possible. The OAuth needs user interaction (confirmation) to grant access to certain API endpoints. You could include a browser module within your Java application and read the final url out of it, but I personally haven't done this yet. Thus I can't provide you with any details on that.

**Comment by plimplom** [comment]
This definitely helps with my problem, but I still dont get how I get the authentification. What are possible ways for me to do it?

**Comment by Dargmuesli** [comment]
What exactly is your question? Do you have troubles understanding the OAuth flow or do you need an explanation on how to use this wrapper's auth methods? Or something different...

**Comment by plimplom** [comment]
Ok I figured it out, since I its only for personal use and not for multiple users, I just generated an URI, got the AuthCode from there and converted it into an access token and a refresh token which works just fine, if I dont generate more URIs.

Thanks alot for the help!
