### ISSUE TITLE
Retrieve Cover of a Track or Album

### ISSUE THREAD

**Issue by ItsTheJetstream** [thelinmichael/spotify-web-api-java#143]
Is it possible to retrieve the Artwork image of a track or album using this library?
According to [this Stackoverflow answer](https://stackoverflow.com/a/18294883/5118384) it can be done. But is there already a built-in way in this library?

**Comment by Dargmuesli** [comment]
Yes, this library fully supports all API endpoints.

There are the README, Javadoc and examples available in this repository that show you how to fetch an album object. Looking at the link you provided, you can see yourself that that is your goal.
