### ISSUE TITLE
Adding multiple tracks to a playlist in a single request doesn't work

### ISSUE THREAD

**Issue by itsaphel** [thelinmichael/spotify-web-api-java#145]
These took a while to debug and identify the issues themselves. Apologies if this report lacks helpful information to resolve the issue - it's 4AM now and I need to catch some sleep so I haven't really had time to figure out why the second issue is occurring.

--------

**First issue**: The example and test is wrong I believe, perhaps a recent update broke this: https://github.com/thelinmichael/spotify-web-api-java/blob/master/examples/data/playlists/AddTracksToPlaylistExample.java

This track ID alone won't work. A full Spotify URI has to be entered as a value.

--------

**Second issue**: Adding more than one track per request (AddTracksToPlaylist request) bugs out. I haven't had a chance to check why exactly, but the SnapshotResult object that it returns is null with no exceptions printed. Tracks are not added to the playlist. Making one request per track, however, works.

According to the [Spotify API docs](https://developer.spotify.com/documentation/web-api/reference/playlists/add-tracks-to-playlist/) up to 100 tracks per request should be possible to be added. I'm guessing they made an API change and the library's method of adding tracks to the request is outdated.

**Comment by itsaphel** [comment]
A quick guess just looking at their doc, perhaps wrong:

A valid request with multiple tracks, from their docs:
`curl -i -X POST "https://api.spotify.com/v1/users/wizzler/playlists/7oi0w0SLbJ4YyjrOxhZbUv/tracks?uris=spotify%3Atrack%3A4iV5W9uYEdYUVa79Axb7Rh,spotify%3Atrack%3A1301WleyT98MSxVHPZCA6M" -H "Authorization: Bearer {your access token}" -H "Accept: application/json"
`

This library encodes the colon into %3A correctly, but also encodes the commas from looking at my debugger earlier today. That might be the issue, and Spotify might treat it as one long track URI that is invalid.

Just a guess, perhaps a wrong one but might be helpful if it's on the right lines. I'll take a closer look tomorrow if I get a chance.

**Comment by Dargmuesli** [comment]
Thanks for the catch, I've updated the example and the unit test. I could not reproduce your second issue though. I'll wait with the release of version 2.0.4 a few days so that you can give me more information on this issue.

**Comment by itsaphel** [comment]
Take a look here: https://github.com/itsaphel/tv-playlist-generator-cli/blob/master/src/main/java/io/indices/tvplaylistgenerator/streaming/Spotify.java#L105-L130

Adding back the commented out code to send more than 1 track per request causes some form of error. An exception is not thrown or printed, but the addTracksToPlaylistRequest var is null and the request isn't successful.

**Comment by Dargmuesli** [comment]
Still works for me, even in your project ([PR](https://github.com/itsaphel/tv-playlist-generator-cli/pull/2)).

**Comment by itsaphel** [comment]
@dargmuesli Still having some troubles with this.

Your PR: https://github.com/itsaphel/tv-playlist-generator-cli/pull/2

Testing on a show with 277 songs (id is "power"). I _think_ your batch code causes some number issues (e.g. on second run, i = 100, subList toIndex = (277 - 100 * 100) = -9000 something.

I replaced with the following batching code: https://github.com/itsaphel/tv-playlist-generator-cli/blob/master/src/main/java/io/indices/tvplaylistgenerator/streaming/Spotify.java#L112-L119

On the first run it has batch fromIndex = 0, toIndex = 99. (I tried 99 batch size because 100 didn't work). snapshotResult is null on this run. Any ideas? Still seems to me like it could be a bug with the library?

You should be able to reproduce with a large show (I used show ID "power"). To run the app you pretty much just need to fill in a clientId, clientSecret and appUrl in a config.json. The authentication code is manually pasted into the CLI.

**Comment by dargmuesli** [comment]
Hmm, dunno what I confused there 3 years ago, but this line should work better
`List<String> subList = trackIds.subList(i, i + 100 - 1);`
The for loop goes in steps `0`, `100`, `200` and now the first sublist uses indices `0` to `0 + 100 - 1 = 99`, then `100` to `100 + 100 - 1 = 199` and so on.
