### ISSUE TITLE
Question: does anyone know the request limit?

### ISSUE THREAD

**Issue by Camaendir** [thelinmichael/spotify-web-api-java#147]
The official Spotify documentation says there is a limit on how many requests you can make. It says the amount of requests is independent from the amount of user currently making requests. Does anyone know how many requests I can make and how it is counted (per day, per hour, etc)

**Comment by Dargmuesli** [comment]
Please see [CONTRIBUTING.md#your-questions](https://github.com/thelinmichael/spotify-web-api-java/blob/master/CONTRIBUTING.md#your-questions).
