### ISSUE TITLE
Example for Pagination

### ISSUE THREAD

**Issue by Bart1909** [thelinmichael/spotify-web-api-java#148]
Is there an example which shows how to page through more results? For example for the sync getCurrentUsersRecentlyPlayedTracks

**Comment by Dargmuesli** [comment]
No, there isn't. Following [thelinmichael's comment](https://github.com/thelinmichael/spotify-web-api-java/issues/27#issuecomment-68264420) on this topic I kept this project as close to the API reference as possible. How the user handles information retrieved from the API is up to them. You can still use classes like the [AbstractDataRequest](https://github.com/thelinmichael/spotify-web-api-java/blob/master/src/main/java/com/wrapper/spotify/requests/data/AbstractDataRequest.java) (or its builder) from this project that may help you building the functionality you desire.

For more information about paging object see [Object Model | Spotify for Developers](https://developer.spotify.com/documentation/web-api/reference/object-model/#paging-object), in your case at *cursor-based paging object*.
