### ISSUE TITLE
ERROR..

### ISSUE THREAD

**Issue by thoughtcastapp** [thelinmichael/spotify-web-api-java#149]
java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes3.dex)
     

I dunno what to do.

Also, can u please tell me how to get UseriD and Name?

**Comment by Dargmuesli** [comment]
I dunno what you mean.

Also, can you please have a look at the examples provided by this repo?

**Comment by thoughtcastapp** [comment]
I get the above error on this line of code..

`  private static final SpotifyApi spotifyApi = new SpotifyApi.Builder()`

I followed the example for adding a playlist...
If you need more code to see tell me.

Also, about userid and name - is this the acc name?

**Comment by Dargmuesli** [comment]
Could it be that you are referencing the Android API.
