### ISSUE TITLE
Error:Null

### ISSUE THREAD

**Issue by juaguecar** [thelinmichael/spotify-web-api-java#151]
Hello im testing your examples and the ClientCredentialsExample.java always return me Error: Null i just copied it and replaced the client id and the client secret, i dont know why it does't work.
Thanks

**Comment by Dargmuesli** [comment]
I cannot reproduce the problem, everything works for me copying the example and replacing the credentials.

**Comment by juaguecar** [comment]
But only adding the dependency to the pom.xml and copyng the example should work?

**Comment by Dargmuesli** [comment]
Yes, that should do it.

**Comment by juaguecar** [comment]
The point is that the only one that rules for me is the AuthorizationCodeUriExample.java, the rest of the examples result on a error:null

**Comment by Dargmuesli** [comment]
Please hit the debug button then and tell me what you find.

**Comment by juaguecar** [comment]
It was a problem with the http dependency defined on my pom.xml, you can close this issue.  
Thanks for your amazing work!
