### ISSUE TITLE
error trying to get started

### ISSUE THREAD

**Issue by thoughtcastapp** [thelinmichael/spotify-web-api-java#158]
AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.david.stlstr, PID: 20926
    java.lang.NoSuchFieldError: No field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes3.dex)

    private static final SpotifyApi spotifyApi = new SpotifyApi.Builder()
            .setClientId(clientId)
            .setClientSecret(clientSecret)
            .build();

this line is where the error occurs.

**Comment by Dargmuesli** [comment]
Hey, are you able to read the very first line of the README? The answer to this issue is written there, in bold.

**Comment by Dargmuesli** [comment]
Btw: duplicate of #149. same author. Please do not open another issue for that.

**Comment by thoughtcastapp** [comment]
sorry!
