### ISSUE TITLE
how to get a specific playlist in v1,not in user

### ISSUE THREAD

**Issue by mingxin-yang** [thelinmichael/spotify-web-api-java#159]
the endpoint: https://api.spotify.com/v1/playlists/{playlist_id}/tracks

**Comment by Dargmuesli** [comment]
It's unclear what you mean. Please look at the examples provided (https://github.com/thelinmichael/spotify-web-api-java/blob/master/examples/data/playlists/GetPlaylistsTracksExample.java)
