### ISSUE TITLE
Documentation for checking whether user has paused their Track?

### ISSUE THREAD

**Issue by nathan3882** [thelinmichael/spotify-web-api-java#162]
Hi, I was wondering if Spotify had support for checking if the user has paused their track, if not I will have to make an improvised version - I look forward to your reply, thanks :)

**Comment by Dargmuesli** [comment]
Sure, start with [GetUsersCurrentlyPlayingTrackExample.java] (https://github.com/thelinmichael/spotify-web-api-java/blob/master/examples/data/player/GetUsersCurrentlyPlayingTrackExample.java). 

A simple search of [the API documentation](https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-get-information-about-the-users-current-playback) reveals that

> When no track is currently playing, the request will return a 204 NO CONTENT response with no payload.

**Comment by nathan3882** [comment]
> Sure, start with [GetUsersCurrentlyPlayingTrackExample.java](https://github.com/thelinmichael/spotify-web-api-java/blob/master/examples/data/player/GetUsersCurrentlyPlayingTrackExample.java).
> 
> A simple search of [the API documentation](https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-get-information-about-the-users-current-playback) reveals that
> 
> > When no track is currently playing, the request will return a 204 NO CONTENT response with no payload.
> 
> Is that what you mean?

No, as you say, it returns a 204 no content, but that's when they haven't pressed play at all, perhaps not opened spotify? But anyways - what I was wondering is whether you could check if the user has a track is paused - isPlaying will still return true, yet it is paused and no audio is coming out.

Like so http://prntscr.com/mrauht

Thanks.

**Comment by Dargmuesli** [comment]
Combine it with [get-a-users-available-devices](https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-get-a-users-available-devices) and you should be good.

**Comment by nathan3882** [comment]
Hi @dargmuesli,

I would appreciate it greatly if you could clarify how I'm meant to utilise a function in which that returns available devices; I'm confused as it could return 3 devices - my android device, my iPad or my desktop could all be returned.

Thanks & look forward to your response.

**Comment by dargmuesli** [comment]
I thought you wanted to target a specific device. When a track is stopped, `isPlaying` should return false.

**Comment by nathan3882** [comment]
I don't know how this managed to slip by my tests etc on the 27th Feb, who knows!

Thanks! :)

**Comment by dargmuesli** [comment]
The CurrentlyPlayingContext also includes the device as well as the repeat and the shuffle state.

**Comment by dargmuesli** [comment]
See [get-information-about-the-users-current-playback/#currently-playing-context](https://developer.spotify.com/documentation/web-api/reference/player/get-information-about-the-users-current-playback/#currently-playing-context) and [get-the-users-currently-playing-track/#currently-playing-object](https://developer.spotify.com/documentation/web-api/reference/player/get-the-users-currently-playing-track/#currently-playing-object).
