### ISSUE TITLE
GetPlaylist: null

### ISSUE THREAD

**Issue by r34ple** [thelinmichael/spotify-web-api-java#163]
Hi,

first of all: Thanks for your work! Exactly what I need for working with the Spotify API.

I just c&ped your playlist files and when I try to for example use GetPlaylistsTracksExample.java, I just get null as the total value of available tracks. The same GetPlaylistExample.java with the playlist's name.
I just replaced my access token and the track examples are working (i.e. I can successfully retrieve the name of a track).

Could you try that by yourself? I would appreciate that.

Thanks!

**Comment by dargmuesli** [comment]
I'll test it soon. Just due to experience from past issues: could you show me your code in the meantime?

**Comment by dargmuesli** [comment]
Nvm, I was able to reproduce the bug.

**Comment by dargmuesli** [comment]
Well, seems like I fell for the same obvious copy paste mistake. Remove the second and third of those four lines. They are just ... examples.

```
  private static final GetPlaylistRequest getPlaylistRequest = spotifyApi.getPlaylist(playlistId)
          .fields("description")
          .market(CountryCode.SE)
          .build();
```
