### ISSUE TITLE
"Error: Unauthorized"

### ISSUE THREAD

**Issue by diegowinter** [thelinmichael/spotify-web-api-java#164]
I've got this error when I was trying to upload a custom playlist cover. I'm sure that I'm using right scopes and I've tried some different images and playlists. Could you try to reproduce this issue? Thanks in advance.

**Comment by dargmuesli** [comment]
Did you read [the docs](https://developer.spotify.com/documentation/web-api/reference/playlists/upload-custom-playlist-cover/)? Have you created your token with `ugc-image-upload` & `playlist-modify-public` / `playlist-modify-private` scopes?
