### ISSUE TITLE
Help retrieven both AccessToken and RefreshToken

### ISSUE THREAD

**Issue by ArKaGarCa** [thelinmichael/spotify-web-api-java#167]
Hi,
I'm trying to make a terminal app that show all the information about the user's playback. I've setted up an HTTP Server for the uri callback, and the code seems to be just fine, but when I try to call authorizationCodeRequest.execute() it steps into the catch clause, being unable to get both the AccesToken and the RefreshToken.
I can't seem to find the problem, both the callback URI on the code and on spotify apps is the same.

**Comment by dargmuesli** [comment]
**Never** [publish your application's client secret](https://github.com/ArKaGarCa/Spotify-Terminal-Playback/blob/a13e0e606537640600170811a02470226a853669/spotifyterminal/src/main/java/app/App.java#L33).

Is there any chance you could tell me the error message you receive inside the catch clause you referred to?

**Comment by ArKaGarCa** [comment]
With "code" I don't mean client secret, but the code that gets sent to the URI I set on the app configs on Spotify apps page and the one you defined as redirectUri on your code.
I can get the authCode succesfully stripping it from the query sent to the local HTTP Server, but when i call `final AuthorizationCodeCredentials authorizationCodeCredentials = authorizationCodeRequest.execute();` it prints "Error: Invalid authorization code".

**Comment by ArKaGarCa** [comment]
I 've just realized what you meant by mentioning my app's client secret, thanks for making me notice it.

**Comment by dargmuesli** [comment]
Could you please double check that the code doesn't contain any other query parameters?

**Comment by ArKaGarCa** [comment]
It's just 1 parameter on the query in the form of .../?code=... , and the code wich I get. I don't know if there's a specific form of the code, I just recieve a string with mixed letters, numbers and characters

**Comment by dargmuesli** [comment]
Please post an example.

**Comment by ArKaGarCa** [comment]
`http://localhost:8080/?code=w6wtZiogwh6tPn6DK5Dr9g5gl6rZD3zXaYm-wwPheP1sw3LOh7yEs2wW76lIfEVkT7SYl55Y6imeaPWHfCDdal15ZY8rP-M1arn7aDPHdx16aWtvwt6YCPsKDc46-w8jKOtykTv6ripD2nHW4MsrtgePXZKIN1rdPXar7eazErglJ-PrdHvYahkjO13E`
I changed some letters from the code, and it's the same for every time I run the app with my Spotify user. What I use on the AuthorizationCodeRequest as a code is 
`w6wtZiogwh6tPn6DK5Dr9g5gl6rZD3zXaYm-wwPheP1sw3LOh7yEs2wW76lIfEVkT7SYl55Y6imeaPWHfCDdal15ZY8rP-M1arn7aDPHdx16aWtvwt6YCPsKDc46-w8jKOtykTv6ripD2nHW4MsrtgePXZKIN1rdPXar7eazErglJ-PrdHvYahkjO13E``

**Comment by dargmuesli** [comment]
That looks good. I'll take a look at your project when I have the time for it :)

**Comment by ArKaGarCa** [comment]
Thanks for the help, I'll wait for your response then :D

**Comment by ArKaGarCa** [comment]
Hi, were you able to try it out?

**Comment by dargmuesli** [comment]
https://github.com/ArKaGarCa/Spotify-Terminal-Playback/blob/81637c38d2dc07cc26dcaf38715a740270fb9235/spotifyterminal/src/main/java/app/App.java#L39 creates the authorization code request with `code = "null"` from line 35 on class initialization, not after retrieving the code.
