### ISSUE TITLE
Album.getCopyrights()[i].getType() is always null

### ISSUE THREAD

**Issue by marco-eckstein** [thelinmichael/spotify-web-api-java#168]

**Comment by dargmuesli** [comment]
Please provide an exact scenario so that I can try to reproduce it. This is currently not enough information.

**Comment by marco-eckstein** [comment]
Just `spotifyApi.getAlbum(id).build().execute()`. E.g., `id == "2Kh43m04B1UkVcpcRa1Zug"`.

**Comment by dargmuesli** [comment]
Thanks for the clarification. The last release of a bug fix had issues with the CI. I'm currently short on time so there might be a delay until this is fixed properly. Maybe I'll need the help of the original owner too, which would make it even more complicated. Let's see.

**Comment by dargmuesli** [comment]
Yep: `Unusable secret key`. That'll take some time, sorry.

**Comment by dargmuesli** [comment]
Well, being me I took the time. The release `2.2.1` should be available shortly.

**Comment by marco-eckstein** [comment]
Thank you! I can confirm this works in 3.0.0.

**Comment by dargmuesli** [comment]
Great to hear, thank you for the feedback!

**Comment by dargmuesli** [comment]
It should work with `2.2.1` too, but that hasn't yet appeared on Maven Central somehow. `3.0.0` removed support for JDK 1.7.
