### ISSUE TITLE
nullPointerException after fetching currentlyPlayingContext

### ISSUE THREAD

**Issue by ArKaGarCa** [thelinmichael/spotify-web-api-java#171]
Hi, as the title says, I'm getting this error while trying to check if the user is listening to something. This only happens if the user isn't listening to music when the code runs. On the opposite case, everything works well. I think the problem resides in the getInformationAboutUsersCurrentPlaybackRequest execution. Below is the part of the code that throws this error while compiling:

```
CurrentlyPlayingContext currentlyPlayingContext = null;
Track currentSong;
while (true) {
   try {
      if (!updatingAccess.get()) {
         currentlyPlayingContext = playbackStatus.execute();
         if (currentlyPlayingContext.getIs_playing()) {
            currentSong = currentlyPlayingContext.getItem();
            if (currentSong == null) {
                  refreshNonPlayingSongData();
            } else {
               if (currentSong.equals(previousSong)) {
                  setCurrentLength(currentlyPlayingContext);
                } else {
                   previousSong = currentSong;
                   refreshSongData(currentlyPlayingContext);
                }
              }
         } else {
            refreshNonPlayingSongData();
          }
      }
   } catch (SpotifyWebApiException | IOException e1) {
       e1.printStackTrace();
   }
      try {
         Thread.sleep(1000);
      } catch (Exception e) {
         System.out.println(e.getMessage());
      }
   }
```

**Comment by dargmuesli** [comment]
Please include a full, testable code example. All functions within the excerpt you provided are unknown to me, especially `playbackStatus.execute()`. What version of the library are you using?

Without providing basic information, you cannot expect people to be able to help.

**Comment by dargmuesli** [comment]
Feel free to reopen if necessary.

**Comment by ArKaGarCa** [comment]
Sorry for the late response, I'll post the whole code in a pastebin (The project is uploaded on github, but for security reasons I'd prefer to keep it private).

The code: https://pastebin.com/zMBJzKGz

Both the clientID and the clientSecret are deleted for obvious reasons, but I think replacing them with yours should do the trick.

**Comment by dargmuesli** [comment]
What would be the result you expect?
I recommend reading [the documentation for this endpoint](https://developer.spotify.com/documentation/web-api/reference/player/get-information-about-the-users-current-playback/) where it says:

> When no available devices are found, the request will return a 200 OK response but **with no data populated**.
