### ISSUE TITLE
Missing some informations in searchAlbums method

### ISSUE THREAD

**Issue by kykysenpai** [thelinmichael/spotify-web-api-java#174]
Hi,

First of all, your library is awesome, really gets the work done and it's pretty easy to use.

I'm trying to get informations on albums with a search using the searchAlbums method, for example as such : 

`searchAlbums("artist:Our Last Night tag:new").build().execute();`

Upon making this request on the console (https://developer.spotify.com/console/get-search-item/?q=Muse&type=&market=&limit=&offset=), I get informations such as the total tracks and the release date which I can't find in the AlbumSimplified generated instance from the library.

Do you plan on adding said fields ?

I'm using the release 4.0.2

**Comment by dargmuesli** [comment]
Interesting, good catch!
It's true that some values appear to be missing in the simplified album's model object when comparing it to the [specification](https://developer.spotify.com/documentation/web-api/reference/object-model/#album-object-simplified). Those can be added for sure. Could be a chance for you to get started with the current [Hacktoberfest](https://hacktoberfest.digitalocean.com/)? :)
But I noticed that `total tracks` are not part of the specification... I'm not sure about what to do with that. Maybe raise an issue at [Spotify's web API issue tracker](https://github.com/spotify/web-api)?

**Comment by waynee95** [comment]
I would like to work on this, if no one already works on it.

**Comment by dargmuesli** [comment]
Nice, go ahead! ❤️

**Comment by waynee95** [comment]
Since the specification does not talk about `total tracks`, I leave that out?

**Comment by dargmuesli** [comment]
You could add a copy of the model class that contains `total tracks` to [special objects](https://github.com/thelinmichael/spotify-web-api-java/tree/develop/src/main/java/com/wrapper/spotify/model_objects/special).

**Comment by wseemann** [comment]
I created a PR for this here: https://github.com/thelinmichael/spotify-web-api-java/pull/176

**Comment by dargmuesli** [comment]
Release 4.1.0 is on it's way 🔥
