### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Heatmanofurioso** [thelinmichael/spotify-web-api-java#182]
Hello,

Is it possible to add a changelog to the project, in order to better know what is changed in each release?

Thank you

**Comment by dargmuesli** [comment]
Did you check the [releases page](https://github.com/thelinmichael/spotify-web-api-java/releases)?

**Comment by Heatmanofurioso** [comment]
I'm dearly sorry.
Wasn't finding it

**Comment by dargmuesli** [comment]
No problem :)
