### ISSUE TITLE
Issue setting position_ms in the play() function

### ISSUE THREAD

**Issue by Alexander-AJ-Berman** [thelinmichael/spotify-web-api-java#185]
While resuming a user's playback, it appears the play function does not correctly check input for the "position_ms" field to set a user's playback to that exact position.

**Comment by dargmuesli** [comment]
I'll take a look at it soon.

**Comment by dargmuesli** [comment]
Did you specify a `context_uri`? The [developer console](https://developer.spotify.com/console/put-play/) exhibits the same behavior, i.e. only giving a `position_ms` resumes the playback from where it paused, not from the given position.

**Comment by Alexander-AJ-Berman** [comment]
Hey! I did specify `context_uri` . Looking at an example data payload from the spotify web api:
`{
  "context_uri": "spotify:album:5ht7ItJgpBH7W6vJ5BqpPr",
  "offset": {
    "position": 5
  },
  "position_ms": 10000
}`
Should set playback to 10000 MS into the track, whereas with your library the track always starts from 0MS (the beginning of the track).

**Comment by dargmuesli** [comment]
Which version of this project are you using? For me everything works correctly with the current version (4.2.0).

**Comment by Alexander-AJ-Berman** [comment]
Was on 4.0.0! Thanks for the tip =)
