### ISSUE TITLE
Authorization without App Id

### ISSUE THREAD

**Issue by johnsky95** [thelinmichael/spotify-web-api-java#192]
Hi.

Thank you for the wrapper.

Is there any way to use the rest, without the Client Id and Secret.
Like, only with the Tokens of the logged in user?

B.r

**Comment by dargmuesli** [comment]
Have a look at Spotify's [Authorization Guide](https://developer.spotify.com/documentation/general/guides/authorization-guide/). You may be looking for the [Implicit Grant Flow](https://developer.spotify.com/documentation/general/guides/authorization-guide/#implicit-grant-flow).
