### ISSUE TITLE
new post API endpoint

### ISSUE THREAD

**Issue by Skalrayi** [thelinmichael/spotify-web-api-java#194]
spotify released a new POST endpoint for putting tracks in queue. Will you add support for the new Endpoint?

**Comment by dargmuesli** [comment]
My time is limited for the next few weeks. Feel free to submit a PR :)

**Comment by Skalrayi** [comment]
well since i don't really know how your internals work and i just know how to use the API i guess i wait and just write my own POST method. but thanks for the answer

**Comment by dargmuesli** [comment]
https://developer.spotify.com/documentation/web-api/reference/player/add-to-queue/

For further reference, as I cannot find this page in the documentations navigation.

**Comment by dargmuesli** [comment]
Closed with #195.
