### ISSUE TITLE
[Support] Way to get playlist of current track.

### ISSUE THREAD

**Issue by nathan3882** [thelinmichael/spotify-web-api-java#196]
Hi there, I hope you are well.

I have spent a while today scratching my head about whether it was possible using Spotify's API to get an instance of Playlist (of some sort, be it simplified or not etc) from a track.

The following is some code that I just wrote that gets me an instance of Playlist from an external URL on a CurrentlyPlaying instance (CurrentlyPlaying#getContext()).  However I feel it is quite dirty and was wondering if there was a more reliable and better way to get the Playlist of a CurrentlyPlaying song's Playlist

     /**
     * Get an instance of {@link Playlist} when supplied with a model that has a Context on it.
     *
     * @param context Context with external URLs fetched from Spotify Model
     * @return An {@link Optional<Playlist>} that is present if we could get a playlist using the ID from one of the external URLs, otherwise empty.
     */
    public Optional<Playlist> getPlaylistFromContext(SpotifyDetailContainer detailContainer, Context context) {
        Optional<String> optionalPlaylistId = Optional.empty();

        // External URLs is equal to the playlist link etc.
        for (String url : context.getExternalUrls().getExternalUrls().values()) {
            if (url.contains("/playlist/")) {
                optionalPlaylistId = Optional.ofNullable(url.split("/playlist/")[1]);
                break;
            }
        }

        if (!optionalPlaylistId.isPresent()) {
            return Optional.empty();
        }

        Optional<Playlist> optionalPlaylist = Optional.empty();

        try {
            optionalPlaylist = Optional.ofNullable(detailContainer.getSpotifyWebApi().getPlaylist(optionalPlaylistId.get()).build().execute());
        } catch (UnauthorizedException unauthorisedException) {
            if (log.isErrorEnabled()) {
                log.error("Unauthorised - we couldn't get the currently playing song for " + detailContainer + ".", unauthorisedException);
            }
            refreshCredentialSet(detailContainer.getSpotifyCredentialSetId());
        } catch (IOException | SpotifyWebApiException e) {
            e.printStackTrace();
        }
        return optionalPlaylist;
    }

If not then I will have to mock up some API tests to ensure the URL doesnt change.

I look forward to your response.

**Comment by dargmuesli** [comment]
Hey there,
I guess this is the only (and intended?) way to do so. To be sure, ask at [spotify/web-api](https://github.com/spotify/web-api).
I'd recommend parsing the `context`.`uri` field instead of the external urls, just to feel a little better :) It should at least be easier to parse than a full HTTP URL.

**Comment by nathan3882** [comment]
Hey :) thank you very much for the response and the suggestion.

Today I have been trying to get previous song's playlists, but have not been successfull - I was wondering if anything comes to your mind about why PlayHistory doesnt contain any context but GetUsersCurrentlyPlayingTrack does return playlists?

Example of GetUsersCurrentlyPlayingTrackRequest response, note it's context and playlist.
![image](https://user-images.githubusercontent.com/8841914/78389586-dc71fe80-75da-11ea-8345-61ab04ad6c7a.png)

Example of GetCurrentUsersRecentlyPlayedTracksRequest response, note it's lack of context:
![image](https://user-images.githubusercontent.com/8841914/78389861-67eb8f80-75db-11ea-9038-aaa33e632169.png)

The first picture is the same song that is in the second picture, just with a nulled out context - makes 0 sense to me so I was wondering if you had any idea why the context is null for a PlayHistory ?

**Comment by dargmuesli** [comment]
I'm not sure what's unclear about my last suggestion, but one again, you might want to have a look at [spotify/web-api/issues/966](https://github.com/spotify/web-api/issues/966) :)
