### ISSUE TITLE
getPlaylistItems returns tracks with null preview urls

### ISSUE THREAD

**Issue by PyroPez** [thelinmichael/spotify-web-api-java#208]
Using v6.0.0-RC1

When calling getPlaylistItems, some tracks return with null preview urls even though querying directly through the Spotify API those tracks do have preview urls.

Code calling getPlaylistItems:

`GetPlaylistsItemsRequest request = spotifyApi.getPlaylistsItems(playlistId).limit(queryLimit)        .offset(offset).market(CountryCode.GB).build();`
`final Paging<PlaylistTrack> response = request.execute();`

This issue can be reproduced getting the playlist with id '5Acf2PaXyl3t5ZFK3tWhJy' where the track with id '68TJaMSstlIuOKpRr1riov' has a preview url in the response from the spotify api but not in the java object returned from the getPlaylistItems method.

`https://api.spotify.com/v1/playlists/5Acf2PaXyl3t5ZFK3tWhJy/tracks?market=GB&limit=50`

[spotifyApiResponse.txt](https://github.com/thelinmichael/spotify-web-api-java/files/4604168/spotifyApiResponse.txt)

This is one example but I've found the same issue for numerous tracks in different playlists belonging to different users.

**Comment by dargmuesli** [comment]
Executing `((Track) response.getItems()[10].getTrack()).getPreviewUrl()` works just fine for me.

**Comment by PyroPez** [comment]
Sorry, looks like it's to do with Spotify's Api itself. Some preview urls seem to return as null if you use app authorisation that don't return as null if you use user authorisation. Closing the issue.

P.s. Thanks for this library. Really useful!
