### ISSUE TITLE
not deprecated methods getting removed

### ISSUE THREAD

**Issue by ToxicMushroom** [thelinmichael/spotify-web-api-java#209]
GetPlaylistsTracksRequest.Builder#getPlaylistsTracks(String playlist_id) was not deprecated but suddenly removed in 6.0.0. I also don't see any change logs related to this or what I should use instead.
Even the [example](https://github.com/thelinmichael/spotify-web-api-java/blob/master/examples/data/playlists/GetPlaylistsTracksExample.java) in the readme is just gone.
I saw that there is getPlaylistsItems but these items have no info about the track as far as I see

**Comment by dargmuesli** [comment]
See this discussion: https://github.com/thelinmichael/spotify-web-api-java/issues/201 and this PR: https://github.com/thelinmichael/spotify-web-api-java/pull/203.
You are correct, there is no deprecation notice, eventhough there could've been one. This major, breaking change was spontaneous, as the [API reference](https://developer.spotify.com/documentation/web-api/reference/)'s naming changed, which wasn't announced by Spotify beforehand (at least afair).
See [this answer](https://github.com/thelinmichael/spotify-web-api-java/issues/208#issuecomment-626255922) (and the linked discussion above) for the current way to work with the new data format.

**Comment by ToxicMushroom** [comment]
I see. I didn't know I had to cast it to Track, thanks
