### ISSUE TITLE
AuthorizationCodeRequest.Builder is not instantiating with the provided client_id and client_secret

### ISSUE THREAD

**Issue by ericblue** [thelinmichael/spotify-web-api-java#210]
While trying an alternative approach to generating a single line AuthorizationCodeRequest, I discovered that each time an exception with an invalid client ID would be thrown.  

The following code works:

`        SpotifyApi spotifyApi = new SpotifyApi.Builder()
            .setClientId(spotifyConfig.getClientId())
            .setClientSecret(spotifyConfig.getClientSecret())
            .setRedirectUri(SpotifyHttpManager.makeUri(spotifyConfig.getRedirectUri()))
            .build();

        AuthorizationCodeRequest authorizationCodeRequest = spotifyApi.authorizationCode(code).build();`

However, the following returns the exception:

`        AuthorizationCodeRequest
            authorizationCodeRequest = SpotifyApi.builder().build()
                                                        .authorizationCode(
                                                            spotifyConfig.getClientId(),
                                                            spotifyConfig.getClientSecret(),
                                                            code,
                                                            SpotifyHttpManager.makeUri(spotifyConfig.getRedirectUri())
                                                        ).build();
`

Looking closer at SpotifyApi lines 354-360, the returned builder is providing clientId and clientSecret as args rather than client_id and client_secret in the method signature.

`public AuthorizationCodeRequest.Builder authorizationCode(String client_id, String client_secret, String code, URI redirect_uri) {
    return new AuthorizationCodeRequest.Builder(clientId, clientSecret)
      .setDefaults(httpManager, scheme, host, port)
      .grant_type("authorization_code")
      .code(code)
      .redirect_uri(redirect_uri);
  }`

This isn't happening with AuthorizationCodeRefreshRequest as the proper arguments are applied.

**Comment by dargmuesli** [comment]
Good catch! Do you need a fix soon or is it ok for me to wait a few days in case other bug reports come in?

**Comment by ericblue** [comment]
Hi Jonas,

Thanks for the quick follow-up.  No, it's not urgent at all.  It can
certainly wait.
