### ISSUE TITLE
Wrong retrun type of getItem() in CurrentlyPlaying class

### ISSUE THREAD

**Issue by knurzl** [thelinmichael/spotify-web-api-java#211]
The CurrentlyPlaying class' function getItem() shoud return a Track object not a IPlaylistItem. If you cast the result as Track object everything works fine.

**Comment by dargmuesli** [comment]
Well [it certainly looks like it should](https://developer.spotify.com/documentation/web-api/reference/player/get-the-users-currently-playing-track/#currently-playing-object). This is intended as either a track or an episode is returned.
