### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by skang188144** [thelinmichael/spotify-web-api-java#212]
Hi,

I'm just learning to use this API, so please bear with me.

I keep getting this error while using the API:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

All I did was insert the Maven dependency of the project into the pom.xml, and just tried to run some authorization code directly from the docs. I'm using JDK 8, and the latest version of the API (6.0.0)

**Comment by dargmuesli** [comment]
https://github.com/thelinmichael/spotify-web-api-java/pull/205

@duncte123 here we are :) could you explain what to do in this case please?

**Comment by skang188144** [comment]
Okay, so this isn't just something on my part.

I was extremely confused looking into the installed libraries for SLF4J, because there wasn't any directories named "impl". Once I did a bit more research, I realized that it might be the wrong dependency for SLF4J...

Any fixes for this would be much appreciated.

**Comment by duncte123** [comment]
> #205
> 
> @duncte123 here we are :) could you explain what to do in this case please?

Different issue from the warning, the end user has an incompatible logger version

**Comment by dargmuesli** [comment]
@duncte123 well you wrote

> [...] applications are expected to implement their own logger implementations.

Would be great if you could explain to them what to do in this case! :)

**Comment by duncte123** [comment]
Well before I can say anything definite for this case I need to know what slf4j impl (with version) @skang188144 added

**Comment by duncte123** [comment]
Actually now that I get a closer look at the issue, just add logback (https://mvnrepository.com/artifact/ch.qos.logback/logback-classic/1.2.3)
Do not use the beta versions as those do not work with the slf4j version used in this library

My apologies for reading the warning incorrectly

**Comment by skang188144** [comment]
I'm sorry--what is this module supposed to do? I'm not great with this, so would you mind explaining what was causing the warning? I was under the impression that the SLF4J libraries would be installed when I put in the dependency in pom.xml for this API.

Anyways, I think that fixed the issue. I also tried using the 6.0.0-RC1 before you responded, and that seemed to get rid of the warning as well.

I'm just confused on what's happening...

**Comment by duncte123** [comment]
Everything that you need to know about the warning is in the URL that it shows. That site explains it better than I could ever do. The short explanation is to just add logback-classic and you're good to go

**Comment by skang188144** [comment]
Right, I understand that SLF4J couldn't load the StaticLoggerBinder class in, but I'm trying to understand why, and how the logback-classic works.

Also, it didn't work. I added it to my dependencies, and the error still persists.

**Comment by duncte123** [comment]
logback-classic adds the `StaticLoggerBinder` class for slf4j to load in, that is how it knows something is installed.
Make sure that you DID NOT install an alpha/beta version those WILL NOT WORK with the current slf4j implementation

**Comment by skang188144** [comment]
I installed logback-classic 1.2.3, non-alpha or beta, but it's not working.

Also, shouldn't these classes be included in the dependencies the Spotify API installs?

**Comment by duncte123** [comment]
> Also, shouldn't these classes be included in the dependencies the Spotify API installs?

No, it should not, there are a lot of different libs like logback-classic, slf4j-simple and log4j that all hook into slf4j-api.

A library should ONLY ever include the API and let the end-user decide what implementation to use.
Also, I don't know anything about maven so you might have done something wrong there with adding it.

**Comment by skang188144** [comment]
Got it.

Well, it's not working, but at least all my questions were answered. Thank you.
