### ISSUE TITLE
Add common methods of PlaylistItem implementations to interface

### ISSUE THREAD

**Issue by robinfriedli** [thelinmichael/spotify-web-api-java#213]
Hi,

The current `PlaylistItem` implementations `Track` and `Episode` share quite a few methods, such as:
- getDurationMs
- getExplicit / getIsExplicit
- getExternalUrls
- getHref
- getId
- getPlayable / getIsPlayable
- getName
- getAudioPreviewUrl / getPreviewUrl

I think it would make the API nicer to work with if those methods were to be pulled up to the interface to avoid a lot of unnecessary downcasting when working with PlaylistItems. If this is done because future implementations might not implement these methods I think adding a second interface that extends PlaylistItem for the current implementations would be nice. Currently it's quite painful to work with playlists because the API user is forced to add unnecessary casts everywhere that may need to be changed or expanded upon in a future API update. For example, if I didn't miss anything, getting the endpoint URL for all tracks in a playlist looks like this now:
```java
Paging<PlaylistTrack> paging = spotifyApi.getPlaylistsItems(playlistId).offset(offset).limit(limit).build().execute();
List<String> urls = Arrays.stream(paging.getItems())
    .map(PlaylistTrack::getTrack)
    .map(track -> {
        if (track instanceof Track) {
            return ((Track) track).getHref();
        } else if (track instanceof Episode) {
            return ((Episode) track).getHref();
        }

        // will break at runtime if future API version adds additional implementations
        throw new UnsupportedOperationException();
    })
    .collect(Collectors.toList());
```
Such use cases would be easier to implement and work more reliably if there would be a common interface that exposes common methods. Pulling the currently shared methods up to the interface would be most convenient but if that's not possible adding a separate interface as an extension of `PlaylistItem` would at least allow the API user to filter results more effectively. Doing so would also eliminate the current naming inconsistencies between the current implementations (e.g. getExplicit vs getIsExplicit).

**Comment by robinfriedli** [comment]
I opened a pull request pulling all common methods of `Track` and `Episode` up to the `IPlaylistItem` interface resolving naming conflicts by sticking with the naming used by `Track` as this is the older and more commonly used class to avoid breaking changes as much as possible.

**Comment by dargmuesli** [comment]
Hey there, thank you for the suggestion! I totally get your point. The repo's owner liked to keep the wrapper as close to the API specification as possible, so I'd like to keep the naming inconsistencies, eventhough I dislike them as much as you do. I'm always a little in smh-mood when looking at those new episodes Spotify crammed into their already existing data structure. I'll later take a look at the details, but for now I think this'll be doable by duplicating your improved code so that we keep the main code as close to the API as possible (as it is now) and add utility classes that include your improved alternative. Then it's up to the user to choose what to use.

**Comment by robinfriedli** [comment]
Is it just renaming existing official API methods that's the problem? Because then I guess I could leave the existing methods in `Episode` and add interface implementations that just call those existing methods. Would still be pretty ugly to have both getExplicit and getIsExplicit on `Episode` but would have the advantage of not breaking existing code.

**Comment by dargmuesli** [comment]
Renaming the existing methods is definitely a problem, as those are a breaking change and I really want to keep mirroring the API specification with this wrapper. Yes, those almost-the-same method names are really weird, but that's what Spotify went with...

I'm cool with the implementation of a second, extending interface.

**Comment by robinfriedli** [comment]
So what about mostly leaving the PR as it is but re-adding the old methods to `Episode`? What I mean is leaving the additions to the `IPlaylistItem` interface but changing `Episode` to something like:
```java
public Boolean getExplicit() {
    return explicit;
}

@Override
public Boolean getIsExplicit() {
    return getExplicit();
}
```

That way you could use the interface while remaining compatible with the current method naming. I'm not sure what the benefit of an additional interface would be, unless you count adding methods to an interface as breaking change, which is the case if a user has their own implementations but I'm not sure that applies here because it's an API entity and user implementations don't really make sense. Unless this is another case of sticking to the official API, in which case I could make an extension interface (something like `RichPlaylistItem` I guess, or would I have to add the `I` prefix to align with the naming of the other interface? Because I'm honestly not a fan of that convention 🙁.).

**Comment by dargmuesli** [comment]
Nah, sorry, your idea of pulling common methods up to the interface is good, really! 🎉
The way Spotify named those new episode properties is just weird, but sadly that's how it is. Sticking to the API specification was this project's goal when I became its maintainer (just like the interface-I convention) and - as much as I understand your point regarding usability - I'll rather keep it that way. Pulling up the common methods would be great, but having almost duplicate methods on classes would only add weirdness.
If Spotify's naming was more reasonable, I'd be happy to accept your PR. I understand your dissatisfaction, but as long as Spotify itself isn't sure what their endpoints return, I don't think this wrapper has to try to be. It just passes what Spotify gives to the user and doesn't try to make up for some rash upstream decisions.
Thanks again for your suggestion! ♥
