### ISSUE TITLE
getting playlist's tracks

### ISSUE THREAD

**Issue by cloudybyte** [thelinmichael/spotify-web-api-java#216]
So basically I have a problem with the getting of tracks of playlists.
Thats what would be my solution, but there is no method to get for example the name of the first track...

`spotifyApi.getPlaylist(playlistID).build().execute().getTracks().getItems()`
I would think that `spotifyApi.getPlaylist(playlistID).build().execute().getTracks().getItems()[0].getName()`
should return the name of the first song, but there is no method with that name...

**Comment by dargmuesli** [comment]
A playlist item must now be cast to `Track`. Playlists can contain podcast `Episode`s too.

**Comment by cloudybyte** [comment]
Well now it says `Cannot cast PlaylistTrack to Track`

`(Track) spotifyApi.getPlaylist(playlistID).build().execute().getTracks().getItems()[0];`

**Comment by dargmuesli** [comment]
`((Track) playlist.getTracks().getItems()[0].getTrack()).getName()` and you're good to go. [Playlist Track](https://developer.spotify.com/documentation/web-api/reference/object-model/#playlist-track-object)s contain the track or an episode. Spotify's API specification is pretty... specific about this :)
