### ISSUE TITLE
Example for Refreshing Token still sets the new Refresh Token

### ISSUE THREAD

**Issue by Hown3d** [thelinmichael/spotify-web-api-java#218]
Hi,
In your example for refreshing the access token, you set the refresh Token of the spotifyAPI to the given refresh token of the AuthorizationCodeCredentials. The problem is that refresh code of this AuthorizationCodeCredentials is null, which you stated in an old issue. Please update the example so that others don't get misleaded like me.

**Comment by dargmuesli** [comment]
Which issue are you referring to?
