### ISSUE TITLE
Add support for Playback SDK (Events)

### ISSUE THREAD

**Issue by ChristopheCVB** [thelinmichael/spotify-web-api-java#219]
Would it be possible to add support for the Playback SDK. It exists for Javascript (Spotify created it) but not for Java :/
It would prevent spamming the Web API every X seconds to get the Playback Status and such.

**Comment by dargmuesli** [comment]
The playback sdk is different from the web api. I haven't found real http api endpoints after a quick look through it. That seems out of scope for this library. Please correct me if I'm wrong. Looks like it's meant to be Javascript only for now.
