### ISSUE TITLE
Adding Several Items to a playlist does not work when nearing the 100 item mark

### ISSUE THREAD

**Issue by Mkittlein** [thelinmichael/spotify-web-api-java#222]
That basically, I needed to chop the track id's in chinks of 50 to make it work.
The spotify documentations states that _"it is likely that passing a large number of item URIs as a query parameter will exceed the maximum length of the request URI. When adding a large number of items it is recommended to pass them in the request body"_ so I assume this library does it by url instead of body by default, maybe a warning in the documentations or examples would be at least a band-aid fix.

**Comment by WagnerChristoph** [comment]
I think in your case you can supply your track IDs in a JSON array to `
SpotifyAPI.addItemsToPlaylist(String playlist_id, JsonArray uris)` which sets the IDs as body parameter.
I also added a hint to the respective method (#223).

**Comment by dargmuesli** [comment]
Fixed by #223. Thank you!
