### ISSUE TITLE
Get the uri of every track in of playlist

### ISSUE THREAD

**Issue by Teeage** [thelinmichael/spotify-web-api-java#225]
I want to check if an track is already exists in a playlist but I cant find a method to get all uris of the tracks that are in a playlist. 

I tried it with these function:
```java
Paging<PlaylistTrack> playlistsItems = spotifyApi.getPlaylistsItems(playerlistId).build().execute();
```

**Comment by dargmuesli** [comment]
Please use code tags for code. I've added them for you: 
`````````
```java
Paging<PlaylistTrack> playlistsItems = spotifyApi.getPlaylistsItems(playerlistId).build().execute();
```
`````````

---

You're using the correct endpoint for what you're trying to achieve!
Reading [the docs for it](https://developer.spotify.com/documentation/web-api/reference/playlists/get-playlists-tracks/) you can see that you'll receive a `Paging` object, as you wrote. That one contains a property `items` which, following the documentation, can contain "an array of [track objects](https://developer.spotify.com/documentation/web-api/reference/object-model/#track-object-simplified) and [episode objects](https://developer.spotify.com/documentation/web-api/reference/object-model/#episode-object-simplified)". So typecast your instances to Tracks and voila: you can access the tracks' URIs :)

**Comment by Teeage** [comment]
Thank you. :)
