### ISSUE TITLE
Question regarding checking the validity of a Spotify ID

### ISSUE THREAD

**Issue by robinfriedli** [thelinmichael/spotify-web-api-java#230]
I want to handle the case where the user enters an invalid ID, preferably before executing the request and receiving a BadRequestException. Normally, when the API does not find any entities for a given ID it throws a NotFoundException, which I already handle. But if the ID does not match the expected format, a BadRequestException is thrown. I've noticed that this is the case when the ID does not have a length of 22. Are there any other such restrictions that would cause a BadRequestException or does it accept any 22 chars long base-62 string? Would it be valid to just check the length of the ID (I already check that it matches [a-zA-Z0-9]+)? Or even better: Does this API wrapper already offer some utility to check the validity of an ID?

**Comment by dargmuesli** [comment]
This wrapper just returns data coming from Spotify's API. You can find possible error codes [here](https://developer.spotify.com/documentation/web-api/#response-status-codes). As the api docs don't really specify which codes occur can occur for each endpoint specifically, this wrapper doesn't include such logic either.

**Comment by robinfriedli** [comment]
But is it documented what exactly constitutes a valid ID? I couldn't find that in the docs. Although I guess this would be a question for the API itself.

**Comment by dargmuesli** [comment]
The only place I know of is [Spotify URIs and IDs](https://developer.spotify.com/documentation/web-api/#spotify-uris-and-ids). I don't know of more detailed specifications but I'm not working at Spotify ;)
You can try your luck at https://github.com/spotify/web-api

**Comment by robinfriedli** [comment]
Will do. Thanks anyway!
