### ISSUE TITLE
Access-Token-Expired exception is not thrown

### ISSUE THREAD

**Issue by gahisee** [thelinmichael/spotify-web-api-java#231]
hi,
here's my code:
			final CompletableFuture<CurrentlyPlaying> currentlyPlayingFuture = getUsersCurrentlyPlayingTrackRequest.executeAsync();
			currentlyPlayingFuture.whenComplete((smsg, sexp) -> {
				String status = "OK";
				if (sexp != null)
				{	// have to catch spotify-token-expired exception here
					status = "Error: " + sexp.getMessage();
				}
				else
				{
					// smsg contains String version of CurrentlyPlaying which we'll get by .join
					MainApp.log("currentlyPlayingTrack async done ");
					try {
						final CurrentlyPlaying currentlyPlaying = currentlyPlayingFuture.join();
						if (currentlyPlaying != null) {
							curSpotifyContext.curTrack = (Track) currentlyPlaying.getItem();
							curSpotifyContext.isPlaying = currentlyPlaying.getIs_playing();
							curSpotifyContext.progressTime = currentlyPlaying.getProgress_ms();
						} else {
							status = "null curTracks: " + ++nullCurTracks;
							MainApp.log("getUsersCurrentlyPlayingTrack_Async: 000000000000 null return");
						}
					} catch (CompletionException | CancellationException cexp)
					{
						status = "Error: " + cexp.getMessage();
					}
				}
				if (!status.startsWith("OK"))
					curSpotifyContext.curTrack = null;
				callBack.onSpotifyUpdate(SPOTIFY_REQUEST.SREQ_CurrentTrack, status);
			});
		} catch (Exception  e) {
			curSpotifyContext.curTrack = null;
			String err = "Error: " + e.getMessage();
			callBack.onSpotifyUpdate(SPOTIFY_REQUEST.SREQ_CurrentTrack, err);
			MainApp.log(err);
		}

Only way to detect token-expired is to specifically check for the 2nd parameter in the completion function.
It would be more intuitive to have it inside the catch; which is the way it worked for the Sync version.

**Comment by dargmuesli** [comment]
Please use [code formatting](https://www.markdownguide.org/basic-syntax#code-blocks-1).

**Comment by gahisee** [comment]
sorry about that. this should look better....

```		try {
			bInProgress = true;
			final CompletableFuture<CurrentlyPlaying> currentlyPlayingFuture = getUsersCurrentlyPlayingTrackRequest.executeAsync();
			currentlyPlayingFuture.whenComplete((smsg, sexp) -> {
				String status = "OK";
				if (sexp != null)
				{	// have to catch spotify-token-expired exception here
					status = "Error: " + sexp.getMessage();
				}
				else
				{
					// smsg contains String version of CurrentlyPlaying which we'll get by .join
					MainApp.log("currentlyPlayingTrack async done ");
					try {
						final CurrentlyPlaying currentlyPlaying = currentlyPlayingFuture.join();
						if (currentlyPlaying != null) {
							curSpotifyContext.curTrack = (Track) currentlyPlaying.getItem();
							curSpotifyContext.isPlaying = currentlyPlaying.getIs_playing();
							curSpotifyContext.progressTime = currentlyPlaying.getProgress_ms();
						} else {
							status = "null curTracks: " + ++nullCurTracks;
							MainApp.log("getUsersCurrentlyPlayingTrack_Async: 000000000000 null return");
						}
					} catch (CompletionException | CancellationException cexp)
					{
						status = "Error: " + cexp.getMessage();
					}
				}
				if (!status.startsWith("OK"))
					curSpotifyContext.curTrack = null;
				callBack.onSpotifyUpdate(SPOTIFY_REQUEST.SREQ_CurrentTrack, status);
			});
		} catch (Exception  e) {
			curSpotifyContext.curTrack = null;
			String err = "Error: " + e.getMessage();
			callBack.onSpotifyUpdate(SPOTIFY_REQUEST.SREQ_CurrentTrack, err);
			MainApp.log(err);
		}
```

**Comment by dargmuesli** [comment]
- you can edit your original post
- you can add syntax highlighting, for Java write "java" right after the first three backticks
- you can remove the unnecessary indentation that makes your code overflow to the right

With that out of the way, please explain at which point you want the exception to be thrown instead. The (non)existence of an exception can only be determined as soon as the future is resolved. That looks to be the case within `whenComplete`. Everything outside of that only knows about the `currentlyPlayingFuture`, not the `currentlyPlaying` object that will be computed. And a future cannot throw custom exceptions like a SpotifyException, as its just a plain future, which doesn't know what it has inside. Thus, I'm pretty sure that what you intend is not possible as you imagine.

**Comment by gahisee** [comment]
thanks for the lesson on formatting and futures.
my issue was not location but apparent absence of the token-expired exception.
it might help the next user if such limitation in async call was documented somewhere.

**Comment by dargmuesli** [comment]
I'd be happy to merge a PR! :)
