### ISSUE TITLE
AudioAnalysisSegment - Attributes missing

### ISSUE THREAD

**Issue by 0Tom2020** [thelinmichael/spotify-web-api-java#237]
Hey,

I was just developing, then I noticed that I was missing attributes in the com.wrapper.spotify.model_objects.miscellaneous.AudioAnalysisSegment class. 
These are the following:
- duration
- start
- confidence

The Spotify API outputs these attributes with data, but the Java class does not have these attributes.

Is another API call required for this or is this an error?

**Comment by dargmuesli** [comment]
What you're looking for is the `measure` property: https://github.com/thelinmichael/spotify-web-api-java/blob/d33203e91d9a8679d0957b67c3ba453552940ae0/src/main/java/com/wrapper/spotify/model_objects/miscellaneous/AudioAnalysisSegment.java#L17
As the audio analysis segment isn't part of the main model object specification, we combined those properties in a separate class, as they are used in multiple places.
