### ISSUE TITLE
java.net.UnknownHostException 

### ISSUE THREAD

**Issue by talentedasian** [thelinmichael/spotify-web-api-java#238]
I am writing this code on a an ENDEAVOUROS linux distro and had an exception when trying to login using facebook. I am getting a `java.net.UnknownHostException: accounts.spotify.com: Temporary failure in name resolution` and have no other information at all. I am seeking help for this as I cannot get answer from my google searches.

**Comment by dargmuesli** [comment]
> I am writing this code

What code? If you show some of it, I could be able to help.

> trying to login using facebook

Is that related to this project?

> UnknownHostException: Temporary failure in name resolution

First sounds like a local DNS / networking issue to me. Sadly, nothing I could help you with in this context.

> no other information at all

Feel free to add any if something comes up, but until then I'm sorry, I'd have to close this issue in a few days.
