### ISSUE TITLE
Element groupId is not allowed here

### ISSUE THREAD

**Issue by BreakingTV** [thelinmichael/spotify-web-api-java#239]
When I print the dependency I can't Import them

Jitpack is working but the web api not

![image](https://user-images.githubusercontent.com/73740737/106139067-3dbc1d00-616d-11eb-9560-9a76bda194bc.png)

can somone help me?

**Comment by dargmuesli** [comment]
That's something to ask on StackOverflow :)
Please keep this issue tracker to actual issues with the library's code itself.

**Comment by dargmuesli** [comment]
psst: you're missing `<dependency>` tags.
