### ISSUE TITLE
Search item type - artist ArrayIndexOutOfBoundsException when getting images

### ISSUE THREAD

**Issue by talentedasian** [thelinmichael/spotify-web-api-java#240]
I've been getting an ArrayIndexOutOfBoundException when getting images from the artist type in search item. Didn't had this before so it's confusing me as to why it's giving me this.

CODE IS HERE : 

```
List<String> duplicate = new ArrayList<>();

for (Artist artists : result.getArtists().getItems()) {
					if (!duplicate.contains(artists.getName())) {
						duplicate.add(artists.getName());
						artistToResponse.add(itemMethods.cacheAndPutArtists(artists.getName(),artists.getId(), 
								artists.getImages()[0].getUrl()));
						response.put("Artists" , artistToResponse);
					}
			}
```

**Comment by dargmuesli** [comment]
Hey @talentedasian, great to see that you are using this library.

As with [your last issue](https://github.com/thelinmichael/spotify-web-api-java/issues/238), I'd like to point out that this repository's issues are meant to be used for actual bugs and feature requests. Questions are to be asked on StackOverflow, as mentioned at the beginning of this project's [CONTRIBUTING.md](https://github.com/thelinmichael/spotify-web-api-java/issues/238). Please read this before posting any other issues, thanks!

You receive this error as there seems to be an artist object in your look which has no images. You cannot access the first image (`[0]`) then.
