### ISSUE TITLE
How To Handling Exception..

### ISSUE THREAD

**Issue by leeseojune53** [thelinmichael/spotify-web-api-java#242]
I want Handling Exception. for example "Error: Invalid playlist Id"
Api was not thrown Exception. So i don't Handling Exception
help me !!

**Comment by dargmuesli** [comment]
> help me !!

Please read https://github.com/thelinmichael/spotify-web-api-java/blob/master/CONTRIBUTING.md#your-questions. I'm going to close this issue in three days in case you have no more details to share that would allow to help.

**Comment by leeseojune53** [comment]
I found it thank you!
