### ISSUE TITLE
Follow, Unfollow, Check if User is Following endpoints

### ISSUE THREAD

**Issue by thelinmichael** [thelinmichael/spotify-web-api-java#25]
Add https://developer.spotify.com/web-api/web-api-follow-endpoints/

**Comment by gsugambit** [comment]
hey @thelinmichael , i see a lot of people asking for the follow stuff. It's okay to pull and add this functionality right?

**Comment by Dargmuesli** [comment]
Of course it is!
Help of any kind is always... Helpful :D

**Comment by gsugambit** [comment]
Oh ok perfect. I have a cruise coming up but Ill try to start contributing!

**Comment by Dargmuesli** [comment]
Will be part of v2.

**Comment by Dargmuesli** [comment]
I'll close this. Please follow #102 for updates.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
