### ISSUE TITLE
Add changelog with relevant release info

### ISSUE THREAD

**Issue by Heatmanofurioso** [thelinmichael/spotify-web-api-java#250]
Hi.

Many times, I see updates for the library are available, but there isn't any release notes here on the Github page, nor does the project have a changelog.

I understand that it would be an extra piece of documentation to maintain, but it would definitely help developers understand when they want/can/should update the dependency, and when there's breaking changes, what they should do about it.

**Comment by dargmuesli** [comment]
What about https://github.com/thelinmichael/spotify-web-api-java/releases?

**Comment by Heatmanofurioso** [comment]
Thank you for adding/updating those now.

**Comment by dargmuesli** [comment]
The latest three minor versions only added log statements, as you've seen. I'll update the changelog whenever there are changes worth mentioning.
