### ISSUE TITLE
error: package org.apache.hc.core5.http does not exist

### ISSUE THREAD

**Issue by NicholasCousar** [thelinmichael/spotify-web-api-java#253]
I'm trying to compile the client credential examples with `javac -cp target/spotify-web-api-java-6.5.4.jar examples/authorization/client_credentials/ClientCredentialsExample.java`, but I'm getting this error:
`error: package org.apache.hc.core5.http does not exist
import org.apache.hc.core5.http.ParseException;
                               ^
examples/authorization/client_credentials/ClientCredentialsExample.java:33: error: cannot access HttpException
    } catch (IOException | SpotifyWebApiException | ParseException e) {
             ^
  class file for org.apache.hc.core5.http.HttpException not found
2 errors
`
Is there something I need to change in the pom file?

**Comment by dargmuesli** [comment]
I guess you need to install dependencies and compile using Maven?
