### ISSUE TITLE
proxy problem

### ISSUE THREAD

**Issue by rubenh2905** [thelinmichael/spotify-web-api-java#254]
set proxy is not working

**Comment by dargmuesli** [comment]
Please provide an example.

**Comment by dargmuesli** [comment]
Let's reopen this when a helpful example is available.

**Comment by TheKinrar** [comment]
I had a look and can't understand how it should even work. The `setProxyUrl` method in the builder will eventually propagate the value to the SpotifyApi object, but then this value is never used in any way.

The proxy settings in the SpotifyHttpManager.Builder class seem to do something though, so I guess the methods in SpotifyApi.Builder are leftovers from an old way of doing it, and should either update the default HttpManager in some way or be removed.
