### ISSUE TITLE
Navigating pages

### ISSUE THREAD

**Issue by astellingwerf** [thelinmichael/spotify-web-api-java#27]
There's no easy/obvious/documented way to navigate through result pages. `com.wrapper.spotify.models.Page` has properties with a URL for previous and next page, but the members on the request to use them are private, and not accessible in any way. Could you provide an API and/or documentation on how to do that properly?

It should even be considered whether you want to bother the consumer of the API with paging. Normally (I guess!) the consumer simply wants to iterate through a result set, and doesn't want or need to know that the response from the Spotify server came in four pieces. Lazy loading might still be interesting, though.

**Comment by jrlambs** [comment]
Hey guys, can someone share an example of code they use to get the next page given the URL?  I'm scratching my head figuring out how to take the URL and get the object type I'm supposed to get out of it.  Thanks!

**Comment by Dargmuesli** [comment]
Implemented the paging model object in v2 which is currently under construction.

**Comment by Dargmuesli** [comment]
I'll close this. Please follow #102 for updates.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
