### ISSUE TITLE
1.5.0 jar

### ISSUE THREAD

**Issue by kolletzki** [thelinmichael/spotify-web-api-java#28]
Did I miss something or is there any reason why the latest release (1.5.0) isn't available as jar-release?

**Comment by thelinmichael** [comment]
Thanks for the heads up @kolletzki! Human error - the release process failed when I last ran it and I didn't notice. It's there now though.

![](http://media.giphy.com/media/Y9nOsMrYSQoHS/giphy.gif)

**Comment by astellingwerf** [comment]
Did you consider releasing the release in GitHub as well? As in: https://github.com/thelinmichael/spotify-web-api-java/releases

**Comment by kolletzki** [comment]
@thelinmichael Thanks a lot :relaxed: @astellingwerf I don't think so: "As of version 1.4.5 the artifact is available through Maven Central." (README.md)

**Comment by thelinmichael** [comment]
@astellingwerf, all releasables are available on https://oss.sonatype.org/#nexus-search;quick~spotify-web-api-java. I'll add a link in the README :-)
