### ISSUE TITLE
Search for a Playlist

### ISSUE THREAD

**Issue by digitaldesaster** [thelinmichael/spotify-web-api-java#30]
Hey Michael,

it would be great, if you could add the search for a playlist.

thanks
Alex

**Comment by thelinmichael** [comment]
Hey Alex. Will get to this one shortly :-)

**Comment by rasd** [comment]
Hi, any news on this?

**Comment by Dargmuesli** [comment]
Merged and part of v2 that is under construction!

**Comment by Dargmuesli** [comment]
I'll close this. Please follow #102 for updates.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
