### ISSUE TITLE
Play music from spotify

### ISSUE THREAD

**Issue by miguelpveloso** [thelinmichael/spotify-web-api-java#31]
If I want to build a player, it means play a music from spotify, can I use your wrapper to do it or use the spotify android sdk instead?

Thanks a lot.

**Comment by digitaldesaster** [comment]
you have to use the spotify android sdk to play music, this is for searching content, look at the readme.
regards
Alex

**Comment by thelinmichael** [comment]
@digitaldesaster is correct, this library is only for making requests to the Web API and doesn't support playback. For anyone looking for the Android SDK docs, they're [here](https://developer.spotify.com/technologies/spotify-android-sdk/).

**Comment by Horrgs** [comment]
@thelinmichael what if you're not doing this on Android?
