### ISSUE TITLE
Getting error on Authorization Code Grant

### ISSUE THREAD

**Issue by miguelpveloso** [thelinmichael/spotify-web-api-java#32]
When I try to get authoriztion, the callback is going to the method onFailure, and the error message is "null". I don't understand what is the field "code" that we have to define, and maybe this why I have error on the authorization. Can you help me? Thanks a lot.

PS: this is my code with error http://pastebin.com/X0M4qf40

**Comment by s3ni0r** [comment]
+1

**Comment by AdriaBergeAguilar** [comment]
+1

**Comment by Dargmuesli** [comment]
The [documentation](https://developer.spotify.com/web-api/authorization-guide/#tablepress-68) specifies: 

> code | Required. The authorization code returned from the initial request to the Account's /authorize endpoint.
> -- | --
