### ISSUE TITLE
Please add Categories

### ISSUE THREAD

**Issue by digitaldesaster** [thelinmichael/spotify-web-api-java#34]
Hey Michael, 

they are pushing things forward.

https://developer.spotify.com/web-api/get-categorys-playlists/

i hope you will find some time to add this to the api.

thanks 
Alex

**Comment by Dargmuesli** [comment]
Will be added in v2. Stay tuned!

**Comment by Dargmuesli** [comment]
I'll close this. Please follow #102 for updates.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
