### ISSUE TITLE
Issue with refreshing the access_token using the refresh_token

### ISSUE THREAD

**Issue by shroffrushabh** [thelinmichael/spotify-web-api-java#35]
Hey Michael, first of all, this is an awesome library.  I am trying to get a new access_token using the refreshToken api in this lib but keep on getting a 400 from spotify. Any clue on what I maybe doing wrong?

```
Api api = Api.builder()
        .build();

api.setAccessToken(accessToken);
api.setRefreshToken(refreshToken);
final SettableFuture<RefreshAccessTokenCredentials> refreshAccessTokenCredentialsFuture =
        api.refreshAccessToken().build().getAsync();

final SpotifyResponse[] spotifyResponse = {null};

Futures.addCallback(refreshAccessTokenCredentialsFuture, new FutureCallback<RefreshAccessTokenCredentials>() {
    @Override
    public void onSuccess(RefreshAccessTokenCredentials result) {
        spotifyResponse[0] = new SpotifyResponse(result.getAccessToken(), result.getExpiresIn());
    }

    @Override
    public void onFailure(Throwable throwable) {
        throwable.toString();
    }

});
```

but I constantly get a 400

**Comment by erikhofer** [comment]
Did you solve this? I also get a `400 Bad Request`.

**Comment by mjonik** [comment]
same problem here. error 400.
`{"error":"invalid_client","error_description":"Invalid client"}`

**Comment by anubiann00b** [comment]
Same issue here

**Comment by anubiann00b** [comment]
I had the same issue, but I solved it.

Just add the client ID and client secret when creating the API:

```
Api api = Api.builder()
        .clientId("...")
        .clientSecret("...")
        .build();
```

**Comment by Kaiser1989** [comment]
Tip: Build your api once with your clientId, clientSecret and redirectUri.
Use that instance for all your calls.

Tokens are only valid in combination with your given information

**Comment by Dargmuesli** [comment]
Correct. And since b48db358facee63d86904479f8b4c88327ce6637 these request types will require the information for building.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
