### ISSUE TITLE
How to set proxy host/port ?

### ISSUE THREAD

**Issue by omasseau** [thelinmichael/spotify-web-api-java#36]
Hello, 

how can I set the proxy host/port when behind a proxy ?

Using httpClient I do:
HostConfiguration config = client.getHostConfiguration();
config.setProxy(PROXY_HOST, PROXY_PORT);

But the API does not give me access to the httpClient.

**Comment by Dargmuesli** [comment]
#60 covers this problem. Closing this to keep a better overview.

**Comment by Dargmuesli** [comment]
Sorry, I misread the question. I'll implement this enhancement soon!

**Comment by Dargmuesli** [comment]
Proxy settings added in aee80d66d08608d81e8028ab2014380e641b8251.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
