### ISSUE TITLE
better error handling for getting a playlist with local/unavailable tracks

### ISSUE THREAD

**Issue by martyf6** [thelinmichael/spotify-web-api-java#37]
I noticed if a users playlist contains local tracks, or tracks that aren't available on spotify, a request to retrieve the playlist fails entirely.  Once the loop retrieving each PlaylistTrack reaches the unavailable track, it throws a NPE and the entire request fails.  It would be nice if the request succeeded, but unavailable tracks are omitted, or better yet, a new type of PlaylistTrack is created to handle these types of occurrences where some of the metadata (name, artist, or album) is missing, which causes the NPE.

**Comment by digitaldesaster** [comment]
Yes, it also belongs to kaaes wrapper. i have opened a ticket here.
https://github.com/kaaes/spotify-web-api-android/issues/53

for local mp3 files, the albumtype of the song is null. i think best way would be to ignore these songs. 

you can check this list. 
1121798449
10WUZITIe8MCurCTYMuzQf

**Comment by ClemensSchneider** [comment]
Is there any chance that this issue will be fixed in the near future? Because otherwise I will implement playlist-related calls directly using the REST interface as a workaround.

**Comment by coreygarvey** [comment]
Does anyone have a workaround for this issue?
