### ISSUE TITLE
Unkown Albumtype

### ISSUE THREAD

**Issue by Tobisaninfo** [thelinmichael/spotify-web-api-java#39]
I recently tried to load a user playlist from spotify. The user is vatrixxx and the playlist id is 0XCJhP0wvALybQsWsjSJ5M . I get an exception of the type java.lang.IllegalArgumentException: No enum constant com.wrapper.spotify.models.AlbumType.NULL. Can you change this enum?

**Comment by Tobisaninfo** [comment]
I found out that this type of Album is for local updloads to spotify. But it's way to complicate to edit it by my self. Can you add this enum constant?

**Comment by martyf6** [comment]
This issue is already identified in #37.
