### ISSUE TITLE
UserPlaylistRequest -- page of playlists is incomplete / has null next URL when more exist

### ISSUE THREAD

**Issue by patricktyndall** [thelinmichael/spotify-web-api-java#41]
Hello - 

The Page<SimplePlaylist> returned from UserPlaylistRequest does not seem to be getting all of the available playlists, even when the limit is set to be higher than needed. Also, the URL for the next Page is null. This is preventing me from getting all the available playlists for a user. Please inform / fix! Thanks.

**Comment by imanzano** [comment]
Hi

I fix it in my fork , that is based on the fork of bjozzi/spotify-web-api-java, because bjozzi added the getFeatures methods.

thanks!

**Comment by Dargmuesli** [comment]
His commits were merged here too. This should no longer be a problem. If it still is, reopen!
