### ISSUE TITLE
Api.getStarred(String user) deprecated

### ISSUE THREAD

**Issue by pbauerochse** [thelinmichael/spotify-web-api-java#42]
A while ago Spotify changed their starred tracks behaviour and seemed to have removed the API call to /v1/users/{userId}/starred/tracks. You will now get the starred tracks from a user playlist called "Starred".

Calling Api.getStarred(String user) will therefore cause an Exception

**Comment by tejasna** [comment]
Have the same issue, don't know what exactly "code" is, did you find a work around/solution for this?

**Comment by Dargmuesli** [comment]
Will be part of v2!

**Comment by Dargmuesli** [comment]
Or will be removed in v2 ... 271bc4a7815d8431263e175961786aef3a7adbee. ;)

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
