### ISSUE TITLE
API attemps to override static method

### ISSUE THREAD

**Issue by AFrey95** [thelinmichael/spotify-web-api-java#45]
The API requires the com.google.protobuf jar, but attempts to override a static method within it, which is not allowed by Java.

This error is thrown when attempting to run the example code for Synchronous Usage:
`Exception in thread "main" java.lang.VerifyError: class com.wrapper.spotify.UtilProtos$Url overrides final method getUnknownFields.()Lcom/google/protobuf/UnknownFieldSet;`

I have been unable to resolve this issue by using previous versions of the protobuf jar.

**Comment by thelinmichael** [comment]
@AFrey95, it's been a while so apologies for the late reply. I'd assume that you've moved on to a different library, resolved the issue, or are working on some other exciting project. :-)

The use of Protobuf in this project is arguably unnecessary and should be removed.

**Comment by SriVenkatesan23** [comment]
I have the same error popping up. Did anyone figure out how to get around it?

**Comment by katewayo** [comment]
+1. Any update on a fix? Thanks!

**Comment by Dargmuesli** [comment]
Protobuf was removed in f6dcd7264d4ccdc4f15b8fb61421470f7c4a90b3.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
