### ISSUE TITLE
Correct way of limiting track search to genre

### ISSUE THREAD

**Issue by patrickcorrigan** [thelinmichael/spotify-web-api-java#49]
Hello, this api is great! I'm just wondering if this is the correct way to limit track searches to a genre?

Char letter = "a";
String genre = "rap"; 
final TrackSearchRequest request = api.searchTracks(String.valueOf
                (letter)).query("genre:" + genre).build();

Thank you very much

**Comment by thelinmichael** [comment]
@patrickcorrigan, if your aim is to search for all tracks in the `rap` genre including the letter `a`, then yes. (This is however a very poor search!)
