### ISSUE TITLE
How to get the authorization with show_dialog in it

### ISSUE THREAD

**Issue by pac96** [thelinmichael/spotify-web-api-java#51]
I am following the tutorial in the README on how to authorize a user using the AuthorizationCodeGrant. However, this tutorial does not show any way of incorporating the show_dialog box into it. I understand that an AuthorizationURLRequest object needs to be used, but how do I take that and transform it into a URL I can send to my user?

**Comment by gsugambit** [comment]
yeah i had wrote almost all the code in this library then i found it on github (so mad i wasted all that time) but this is one of the things i wish the project supported. I may pull and add it to the builder. One thing you can do in the short term is add "&show_dialog=true" to the String the api gives you

**Comment by thelinmichael** [comment]
Thanks for opening the issue @pac96! @gsugambit, you're very welcome to contribute to this project. If you're working on a client that you believe has more or other useful features than this one, we'd be interested in linking to it from the Developer site.

**Comment by gsugambit** [comment]
@thelinmichael since you had most implement i deleted most of my code. Made me fill good that we went about everything the exact same way. So Im using your project now as the base. Maybe we can add showDialog to your authorization class and add it onto the builder project?

**Comment by thelinmichael** [comment]
@gsugambit, I agree that adding that would make sense!

**Comment by gsugambit** [comment]
@thelinmichael i think you can close this, looks like you already implemented it. i was about to add it so that i cna make sure contributing to this project was working and then boom, i opened the class and it was there lol

**Comment by gsugambit** [comment]
actually it's not on the api so im going to add it there.

**Comment by gsugambit** [comment]
@thelinmichael created pull request for this issue

**Comment by Dargmuesli** [comment]
Merged. Will be part of v2.

**Comment by Dargmuesli** [comment]
I'll close this. Please follow #102 for updates.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
