### ISSUE TITLE
Thread-Safe Api

### ISSUE THREAD

**Issue by joeyvmason** [thelinmichael/spotify-web-api-java#52]
Is `com.wrapper.spotify.Api` intended to be thread-safe? If so, `refreshAccessToken()` needs to be modified to accept a String argument for the refresh token. Currently, if you call this method without setting a global refresh token, an assertion error occurs. I'm happy to make the change.

**Comment by Dargmuesli** [comment]
This will be fixed in v2. I'll give you an update when I revised the whole API class.

**Comment by Dargmuesli** [comment]
This should've been generally fixed in 168827b0ac08594d9b9182b71fad9edfaca2163e, but some additional thought will go into this. Thanks!

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
