### ISSUE TITLE
No enum constant com.wrapper.spotify.models.AlbumType.NULL

### ISSUE THREAD

**Issue by vmunozre** [thelinmichael/spotify-web-api-java#54]
When i try to get a very large playlist i get this error because some of the tracks may lack the album information. I have seen that this was an issue in some of the wrappers for other languages.

**Comment by thelinmichael** [comment]
Thanks for reporting it @vmunozre!

**Comment by garrit-schroeder** [comment]
Hey Guys,
I was wondering if this bug got fixed already and a new version is going to be published on Maven Central?
Tanks a lot :)

**Comment by Dargmuesli** [comment]
Yes, this was fixed in 22abf451b8f45e90e4cf745a2a13533d34c4a7d4, but I recommend to switch to `v2` of this project *when it's finished*. This kind of error should already generally be taken care of there.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
