### ISSUE TITLE
Support cache-control headers

### ISSUE THREAD

**Issue by erikhofer** [thelinmichael/spotify-web-api-java#59]
It would be great to be able to cache results of the API. Therefore the `Cache-Control` and `ETag` headers would need to be supported.

https://developer.spotify.com/web-api/user-guide/ section "Conditional requests"

> Most API responses come with appropriate cache-control headers set to assist in client-side caching. If you have cached a response, do not request again until the response has expired; if the response contains an ETag, set the If-None-Match request header to the ETag value. If the response hasn’t changed, the Spotify service will respond quickly with the 304 Not Modified status (i.e., your cached version is still good and your application should use it).

**Comment by Dargmuesli** [comment]
Great suggestion! I'll take care of this in v2.

**Comment by Dargmuesli** [comment]
Implemented since d17513bbda111427bc48efab74c71f186a82beca.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
