### ISSUE TITLE
Make the API extensible

### ISSUE THREAD

**Issue by erikhofer** [thelinmichael/spotify-web-api-java#60]
The API lacks some functionality. It would be great if everything that's missing was added to the original project. But personally I, at the moment, don't want to bother with Maven and testing.

It is, however, very hard to add custom functionality to the API. The biggest problem is that you can't extend the `Api` class because it only has a private constructor. Also the method `setDefaults` would not be usable in a child class because it's private, maybe make it protected final.
The `httpManager` of `AbstractRequest` should also be accessible by child classes.

**Comment by Loki-Afro** [comment]
any progress here?

**Comment by Dargmuesli** [comment]
Working on it.

See #102 and [Project v2](https://github.com/thelinmichael/spotify-web-api-java/projects/1).

When all features are implemented, I'll take a look at inheritance.

**Comment by Dargmuesli** [comment]
@erikhofer could you please explain what you meant with "custom functionality"? I think as long as there's full API support (which I'm currently rebuilding) there is no need for those changes in inheritance. The only thing I can think of is that this project will receive less pull requests, because users would rather keep their changes to themselves as they do not depend on official changes any more.

**Comment by erikhofer** [comment]
@Dargmuesli In my case I only needed to extend the API because it wasn't complete. So it would not be necessary when it is complete and gets updated. But there may be use cases that require customizations beyond the scope of this project. In this case (or if there are other reasons for not contributing), it is very cumbersome to do this beacause you still need to maintain a fork.

**Comment by Dargmuesli** [comment]
@Loki-Afro do you have a practical use case for this? I still can't think of one which needs to modify or inherit from our classes. But I'm not fully against the idea of opening it up a little ;)

**Comment by Loki-Afro** [comment]
I had the same use case as @erikhofer but that `setDefaults` method would be handy or some other way to archive the same if one has to extend it for some reason.

Actually there could be a another reason: that whole player api is in the beta stage, so when the json scheme changes or some other minor change one has to wait for an update ...

**Comment by Dargmuesli** [comment]
The `setDefaults` method will move to the builders themselves (900f412647bcf6c94d143ea844aa6c44264bf4c0). I'm closing this one until someone gives us a plausible use case apart from missing features do to the project's inactivity as this period is over for the foreseeable future.

Feel free to further comment on this and reopen if needed.

**Comment by Loki-Afro** [comment]
just let us now when there is a branch to play around with ;)

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released. Please test that one as hard as you can ;)
