### ISSUE TITLE
Publish a new Build to Maven Central

### ISSUE THREAD

**Issue by fallobst22** [thelinmichael/spotify-web-api-java#65]
The pom states the current version as 1.7.1, but the newest one available at maven central is 1.5.0. Would it be possible to publish a new build to maven central, to simplify using the new version?

**Comment by coreygarvey** [comment]
How can I utilize the version 1.7.1 to take advantage of AudioFeatures? I am not able to request these features using 1.5.0.

**Comment by poolebu** [comment]
+1 i have been waitiyfor this too

**Comment by coreygarvey** [comment]
+1 Also waiting for this. Is there an alternative for obtaining the audio summary? Can AbstractRequest be used?

**Comment by gonzarugil** [comment]
+1 still waiting for the fix on getting info for local files

**Comment by ConnorSnee** [comment]
@thelinmichael are there any plans to publish a new build to maven central?

**Comment by Dargmuesli** [comment]
There are, but I still don't have Maven deploy permissions. I'll update the version as soon as @thelinmichael grants them to me!

**Comment by napstr** [comment]
It looks like [jitpack](https://jitpack.io/) builds this repo just fine, so you can have access to the newest code without relying on a builds being published to maven.

Btw, good to see some work being done on this project. :+1:

**Comment by Dargmuesli** [comment]
Mr. Thelin took care of this now. I just released [v1.7.3](https://oss.sonatype.org/#nexus-search;quick%7Espotify-web-api-java) and it should appear on [Maven](https://mvnrepository.com/artifact/se.michaelthelin.spotify/spotify-web-api-java) soon.

**Version 2 of this project will be approximately be released at the end of this week!**

*If you're checking the GPG signature, you need to import mine:*
`gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 60A1E171`

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
