### ISSUE TITLE
If playlist contains local files, request.get() returns empty Page

### ISSUE THREAD

**Issue by nyxaria** [thelinmichael/spotify-web-api-java#66]
If you have a playlist with files that you add from your computer, you cannot retrieve it through the api as it does not support them (?). When you try to, it just returns an empty track list. However, this only occurs if you request for the part that the local file is in, i.e. if it is the 101th song and you request the first 100 it still works, but for the 101th song request it returns empty. If the second request is 100 limit, the whole request is still empty even if there are non-local file songs present.

**Comment by Dargmuesli** [comment]
Partly reproducable on my end. When I try an `getPlaylistTracks` request on a playlist which contains a local file I receive this `IllegalArgumentException`:  #54. Let's solve this first. Then, please tell me if the issure still remains and what request type you are using to reproduce this.
