### ISSUE TITLE
'birthdate' missing from user object and response

### ISSUE THREAD

**Issue by samiruppaluru** [thelinmichael/spotify-web-api-java#67]
Hi,

The 'birthdate' field, which is returned from the "Get Current User" endpoint (GET https://api.spotify.com/v1/me https://developer.spotify.com/web-api/get-current-users-profile/) doesn't seem to be supported by this library yet.

We've already built an integration using this library, and it would be great to be able to use this field, so I'm gonna give a crack at it and try to send in a PR, but figured I would drop this issue here  to reference and see if anyone else has built it, or if the library owner is able to quickly fix it.

Thanks!
-Samir

**Comment by Dargmuesli** [comment]
PR merged!
