### ISSUE TITLE
Reorder a Playlist’s Tracks

### ISSUE THREAD

**Issue by Kaiser1989** [thelinmichael/spotify-web-api-java#69]
Hello,

it would be nice if you can implement the feature of
[https://developer.spotify.com/web-api/reorder-playlists-tracks/](url)

**Comment by dr-carrot** [comment]
Someone wrote this in #46 but it was never merged

**Comment by Dargmuesli** [comment]
This will be part of version 2 on which I'm currently working.

**Comment by Dargmuesli** [comment]
I'll close this. Please follow #102 for updates.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
