### ISSUE TITLE
PlaylistRequest doesn't support parameters.

### ISSUE THREAD

**Issue by Horrgs** [thelinmichael/spotify-web-api-java#71]
`PlaylistRequest request = spotifyManager.api.getPlaylist(userId, playlistId).parameter("limit", "1").build();`

then I go on to ask it how many artists are in the results, it gives me 3 - none of which have collaborated. I also set offsets and that doesn't work too, always starting at 0.

`PlaylistRequest request = spotifyManager.api.getPlaylist(userId, playlistId).parameter("offset", "100").build();`

Neither of which work.

**Comment by Kaiser1989** [comment]
Spotify webapi does not allow parameter offset or limit for getPlaylist.
You have to use getPlaylistTracks instead.

**Comment by Dargmuesli** [comment]
That's correct. Please compare [Get a Playlist](https://developer.spotify.com/web-api/get-playlist/) and [Get a Playlist’s Tracks](https://developer.spotify.com/web-api/get-playlists-tracks/).
