### ISSUE TITLE
Repository never gets updated

### ISSUE THREAD

**Issue by dr-carrot** [thelinmichael/spotify-web-api-java#72]
Someone else should probably take over this repository to allow new changes to be introduced. @thelinmichael

**Comment by poolebu** [comment]
agreed! so many new changes, and no maven access

**Comment by Kaiser1989** [comment]
I also added a feature a month ago, not accepted yet... that's frustrating... especially this is called the "official" spotify java api.

**Comment by Dargmuesli** [comment]
Hey guys and grills,

I just started to read a book about [RESTful Web APIs](https://books.google.de/books?id=ZXDGAAAAQBAJ) that Michael gave to me. Also I need to get up to speed with jUnit tests and the whole structure of this repo.
I currently have other projects I'm working on, but **I volunteered** to maintain ("take over" as you call it) this repository a few months ago. So it's basically my New Year's resolution to work on this project as my others don't seem to be finished in the next weeks. One of these projects builds upon this repo, which makes me interested in seeing progress here.
Sorry for being unresponsive for so long, it seems that I have to get my priorities right. Don't be mad, if you don't hear back from me very soon, as I still need to read and learn some things and want to do everything - yes soon, but also - right.

Wishing you a **happy and progressful New Year**!

**Comment by poolebu** [comment]
Very good news my friend, thank you very much!!! Happy new year!

**Comment by Dargmuesli** [comment]
Hey guys and girls,

it is already March and I tried to contact @thelinmichael several times now. But sadly I did get no response. I don't know why though, because he *read* my messages (Facebook status icon) ...
I wrote him an email a few minutes ago as a last try, but my motivation starts to fade. All I can do is to offer my help.

I'm sorry that - under these circumstances - I can't meet your expactation that I'll be the future maintainer of this project. I would like to, but it seems that the opportunity isn't there any more.

Maybe I'll start an unofficial fork / copy on which pull request are merged. I think the MIT license allows that idea. But of course I do not want to "steal" this project!

So all I can say is sorry, I tried. I hope that this project is going to be updated some day.

Until then! Greetings from Germany
- Jonas Thelemann

**Comment by Dargmuesli** [comment]
Hey guys and girls,

about one year later @thelinmichael finally added me to this project! "Better late than never?!" he says, on which I agree :D
Right now I start studying at my local university so my time is limited. But I'll try to take care of this project whenever I can. I hope this is good news to you! ;)

Greetings from Germany
- Jonas Thelemann

**Comment by garrit-schroeder** [comment]
Really great news!

Am 10.10.2017 20:25 schrieb "Jonas Thelemann" <notifications@github.com>:

**Comment by poolebu** [comment]
Yeah!! I'm very  happy this is happening!

**Comment by thelinmichael** [comment]
Apologies for the delay, people. Not a lot to say except that there's been a lot of things happening in my private life, causing this to be put on the back burner. Looking back, it'd been wise to hand over full access to @Dargmuesli as soon as possible after he made a visit to the Spotify office in Stockholm. 

So, thanks for taking this on @Dargmuesli - much appreciated! I'll ping you regarding deploy rights to the Maven repository. Hopefully I'll be more active in the future, but at least I won't be on the critical path.

If anyone else is interested in helping out, let me and @Dargmuesli know. (You'll have access within a year! Kidding.)

**Comment by Dargmuesli** [comment]
Thanks, I started to dive into this project!
I still need to keep up with university though ;)

**Comment by Dargmuesli** [comment]
Hey guys,
here's a small update on my progress.

I worked on branch "v2" over the last days. It's going to be a complete revision of all project files with breaking changes. I pushed around 100 commits with many more to come. The jungle of classes needs to be cleaned up! It has to be clearly visible which API endpoints aren't implemented yet and it should be easier to add them. We need documented source code #95 and a unified implementation of API endpoint wrappers.

As soon as I'll get *Maven deploy rights*, @thelinmichael, I'll fix all bugs in the current master branch. When v2 is finished, v1 will remain in its own branch and v2 will become master.

I'll be less active within the next weeks though, as I seriously need to focus more on my university education. I spent far too much time using Intellij IDEA in the last week ;)

Any help is appreciated!

A merry christmas to all of you,
Jonas Thelemann

**Comment by Dargmuesli** [comment]
Hey guys,
I have great news for you:

About 450 commits later version **2.0.0-RC1** of spotify-web-api-java was just **released**! Try it.
And try to find bugs ;)

All endpoints are supported now and we have [a great documentation](http://michaelthelin.se/spotify-web-api-java/) as well as good test coverage.

Have fun developing your Spotify API Java software again,
Jonas Thelemann
