### ISSUE TITLE
Play music from spotify

### ISSUE THREAD

**Issue by AdriaBergeAguilar** [thelinmichael/spotify-web-api-java#74]
How can I access the playback of a track from a java application? It's for a game d'office.

Thank you

**Comment by dr-carrot** [comment]
I don't think the spotify web api supports music playback. However the android SDK for spotify is capable of playing music. I would think that it is possible to somehow modify that for use in a desktop application

**Comment by Dargmuesli** [comment]
I guess you are refering to the [Player](https://beta.developer.spotify.com/documentation/web-api/reference/player/) endpoint. This will be included in version 2 of this project on which I'm currently working.

**Comment by Dargmuesli** [comment]
I'll close this. Please follow #102 for updates.

**Comment by Dargmuesli** [comment]
Implemented all Player endpoints in 40c16770c0148cada236b12a32e8853e776d2b7c.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
