### ISSUE TITLE
Getting the HTTP response message

### ISSUE THREAD

**Issue by astarrr** [thelinmichael/spotify-web-api-java#75]
It is possible to retrieve the HTTP response message and read it?

**Comment by Dargmuesli** [comment]
Could you please explain what exactly you are trying to achieve?

**Comment by Dargmuesli** [comment]
In `v2` requests will throw a `SpotifyWebApiException` or in detail: a subtype of it. Filter the root cause and you should have your issue's solution.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
