### ISSUE TITLE
Add getting users playlist like getting users tracks aka .getMyPlaylists()

### ISSUE THREAD

**Issue by noobs2ninjas** [thelinmichael/spotify-web-api-java#76]
Spotify now has an endpoint available to get a users playlists directly at "/v1/me/playlists". See more information [here](https://developer.spotify.com/web-api/console/get-current-user-playlists/).

This would keep us from having to query .getMe() just to retrieve the Id and then having to use getPlaylistsForUser(user.userId())

**Comment by Dargmuesli** [comment]
Will be part of version 2 on which I'm currently working.

**Comment by Dargmuesli** [comment]
Added in bd1599b.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
