### ISSUE TITLE
problem to compile

### ISSUE THREAD

**Issue by ffiore10** [thelinmichael/spotify-web-api-java#77]
Hello all,
I'm new on spotify API and i'm sorry if i ask something that could be obvious for an expert one.
I have download code from repository but when i try to compile project with maven i reached this error:
Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.ListenableFuture

It appears also when i try to launch a method from eclipse using my spotify clientID and clientSecretKey. 

Can someone help me?
Thanks a lot

**Comment by Kaiser1989** [comment]
Seems to be an error in your pom. Create a minimal runable projekt, just include spotify-wep-api and try to compile. Maybe you have other dependencies, which are in conflict with the google guava library used in spotify-web-api (version 18.0).

Pls post your pom.xml for further information.

**Comment by ffiore10** [comment]
Hi Kaiser and thanks for help.
I have not change the original pom . 
`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>se.michaelthelin.spotify</groupId>
    <artifactId>spotify-web-api-java</artifactId>
    <version>1.7.1</version>

    <packaging>jar</packaging>

    <name>Spotify Web API Java Client</name>
    <description>A Java client for Spotify's Web API</description>
    <url>https://github.com/thelinmichael/spotify-web-api-java</url>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>http://www.opensource.org/licenses/mit-license.php</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <url>https://github.com/thelinmichael/spotify-web-api-java</url>
        <connection>scm:git:git://github.com/thelinmichael/spotify-web-api-java.git</connection>
        <developerConnection>scm:git:git@github.com:thelinmichael/spotify-web-api-java.git</developerConnection>
    </scm>

    <developers>
        <developer>
            <name>Michael Thelin</name>
            <email>thelinmichael@gmail.com</email>
            <organization>Michael Thelin</organization>
            <organizationUrl>https://github.com/thelinmichael</organizationUrl>
        </developer>
    </developers>

    <distributionManagement>
        <snapshotRepository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>
    </distributionManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.sonatype.plugins</groupId>
                <artifactId>nexus-staging-maven-plugin</artifactId>
                <version>1.6.3</version>
                <extensions>true</extensions>
                <configuration>
                    <serverId>ossrh</serverId>
                    <nexusUrl>https://oss.sonatype.org/</nexusUrl>
                    <autoReleaseAfterClose>true</autoReleaseAfterClose>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>1.5</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>2.4</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <failOnError>false</failOnError>
                </configuration>
                <version>2.9.1</version>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>2.5.0</version>
        </dependency>
        <dependency>
            <groupId>commons-httpclient</groupId>
            <artifactId>commons-httpclient</artifactId>
            <version>3.1</version>
        </dependency>
        <dependency>
            <groupId>net.sf.json-lib</groupId>
            <artifactId>json-lib</artifactId>
            <version>2.4</version>
            <classifier>jdk15</classifier>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-all</artifactId>
            <version>1.8.4</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>18.0</version>
        </dependency>
    </dependencies>

</project>

`

**Comment by Kaiser1989** [comment]
This is the pom from the spotify-web-api

Where is your pom? Do you want to edit the spotify-web-api, or do you only want to use it?

Something like this:
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>com.my-project</groupId>
        <artifactId>myParent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    
    <artifactId>myModule</artifactId>
    <packaging>jar</packaging>
    
    <dependencies>
  		<dependency>
	  		<groupId>se.michaelthelin.spotify</groupId>
	  		<artifactId>spotify-web-api-java</artifactId>
	  		<version>${spotify-version}</version>
	  	</dependency>
    </dependencies>
	
	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
	</build>
</project>`

**Comment by ffiore10** [comment]
I just want to use it so i add dependency for spotify-web-api..as soon as possible i post the pom of my project

**Comment by ffiore10** [comment]
To avoid every kind of problems i create a new project without other dependencies. Now I'm able to compile the project but i have a problem when invoke a method on spotify API.
I try to replicate this example:
`final Api api = Api.builder()
    			.clientId(clientId)
    			.clientSecret(clientSecret)
    			.build();

    	// Create a request object for the type of request you want to make
    	AlbumRequest request = api.getAlbum("7e0ij2fpWaxOEHv5fUYZjd").build();

    	// Retrieve an album
    	try {
    	  Album album = request.get();
    	  
    	  // Print the genres of the album
    	  List<String> genres = album.getGenres(); 
    	  for (String genre : genres) {
    	    System.out.println(genre);
    	  };
    	  
    	} catch (Exception e) {
    	  System.out.println("Could not get albums.");
    	}`
When it tries to retrieve the album enter in the SpotifyHttpManager and in this point `final String uri = UrlUtil.assemble(url);` get the exception:
`Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableMap$Builder
	at com.wrapper.spotify.UrlUtil.<clinit>(UrlUtil.java:13)
	at com.wrapper.spotify.SpotifyHttpManager.get(SpotifyHttpManager.java:43)
	at com.wrapper.spotify.methods.AbstractRequest.getJson(AbstractRequest.java:34)
	at com.wrapper.spotify.methods.AlbumRequest.get(AlbumRequest.java:31)
	at com.francesco.SimpleParser.App.main(App.java:39)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableMap$Builder
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 5 more`
Have i to add manual this class builder?

**Comment by ffiore10** [comment]
I think that Maps would be loaded from guava libraries..Isn't so?

**Comment by ffiore10** [comment]
I solved the problem using version 19.0 of guava's libraries
