### ISSUE TITLE
Search Tracks by Album

### ISSUE THREAD

**Issue by fabiosakiyama** [thelinmichael/spotify-web-api-java#80]
Hi,

I couldn't find a way to search for tracks given an album, like:

`https://api.spotify.com/v1/search?q=album:albumName&type=track`

Is there anyway?

If not, how should i proceed to add a getTracksByAlbum on Api.java ?

Thanks in advance.

**Comment by Dargmuesli** [comment]
This will be implemented in version 2 on which I'm currently working.

**Comment by Dargmuesli** [comment]
I'll close this. Please follow #102 for updates.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
