### ISSUE TITLE
Get all tracks from a Playlist object using pagination

### ISSUE THREAD

**Issue by Minification** [thelinmichael/spotify-web-api-java#83]
Given a `Playlist` object, there is only the `Playlist#getTracks()` method, which does not seem to offer getting **all** tracks of the playlist (limit is 100).

The problem that I encountered, is the following:

If `api.getPlaylistTracks()` (which does offer support for pagination) is used, the tracks appear to be sorted alphabetically.
If you use `Playlist#getTracks()` having already received a `Playlist` object, the tracks are in proper order, that is, as they are in the playlist checking in the spotify client.

As I really need them in order, I tried to use the `Playlist` object approach, but got stuck since there is no pagination available.

**Comment by Dargmuesli** [comment]
Pagination will be implemented in version 2 on which I'm currently working.

**Comment by Dargmuesli** [comment]
I'll close this. Please follow #102 for updates.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
