### ISSUE TITLE
Start/Resume a User’s Playback

### ISSUE THREAD

**Issue by lilalinux** [thelinmichael/spotify-web-api-java#84]
Since a few days it's possible to start playing using the Web API again:
https://developer.spotify.com/web-api/start-a-users-playback/

Do you plan to implement it in the near future?

**Comment by pzzz** [comment]
Even though now not covered by tests and probably a little messy code, I also need exactly that and started implementing it, see here: https://github.com/pzzz/spotify-web-api-java/tree/player-endpoints

**Comment by gennarosdc** [comment]
Hi, can anyone help me? I `m looking for an endpoint to play a user`s playlist. Is possible at moment? thanks in advance

**Comment by Kaiser1989** [comment]
Check my repo:
https://github.com/Kaiser1989/spotify-web-api-java

**Comment by gennarosdc** [comment]
Yes, I check for User Play request but it does a request to the playback player. Is there any method on Spotify api to play specific playlist? I don't think so..

**Comment by Kaiser1989** [comment]
Use a Playlist identifier as context uri

**Comment by gennarosdc** [comment]
Thank you I solved my problem. But I noticed that at first boot of Spotify client app there is not a playback to resume or start, so the first api call to play/resume return Forbidden message. Is that a way to solve it without start manually a playback at first boot? Thank you a lot

**Comment by Dargmuesli** [comment]
Will be part of version 2 on which I'm currently working.

**Comment by Dargmuesli** [comment]
I'll close this. Please follow #102 for updates.

**Comment by Dargmuesli** [comment]
Implemented all Player endpoints in 40c16770c0148cada236b12a32e8853e776d2b7c.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
