### ISSUE TITLE
Replace Tracks For Playlist

### ISSUE THREAD

**Issue by revolucionx2** [thelinmichael/spotify-web-api-java#87]
How to remove tracks and add new tracks to the playlist?

**Comment by Dargmuesli** [comment]
This is currently not implemented, but it'll be available in version 2 on which I'm currently working.

**Comment by Dargmuesli** [comment]
I'll close this. Please follow #102 for updates.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
