### ISSUE TITLE
No audio playback functionality implemented

### ISSUE THREAD

**Issue by Nanocl** [thelinmichael/spotify-web-api-java#88]
Hi,

unfortunately I found no possibility to play songs as described here:

http://jsfiddle.net/JMPerez/p30pb38z/

or something similar to that. Is it not implemented yet?

**Comment by Loki-Afro** [comment]
I gess this is not implemented because the whole player part is "Beta" https://developer.spotify.com/web-api/web-api-connect-endpoint-reference/

**Comment by Dargmuesli** [comment]
Working on it.

See #102 and [Project v2](https://github.com/thelinmichael/spotify-web-api-java/projects/1).

**Comment by Dargmuesli** [comment]
I'll close this. Please follow #102 for updates.

**Comment by Dargmuesli** [comment]
Implemented all Player endpoints in 40c16770c0148cada236b12a32e8853e776d2b7c.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
