### ISSUE TITLE
AudioFeature and AudioFeatureRequest are missing

### ISSUE THREAD

**Issue by ardausman** [thelinmichael/spotify-web-api-java#89]
Hi there,

I need to use the AudioFeature and AudioFeatureRequest classes but they are missing in version 1.5.0 and the required method is missing in Api class can you make a new release or show me a way to use them

**Comment by Dargmuesli** [comment]
This will be part of version 2 on which I'm currently working.

**Comment by Dargmuesli** [comment]
I'll close this. Please follow #102 for updates.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
