### ISSUE TITLE
Can't get to a track (Error 401)

### ISSUE THREAD

**Issue by Pr1ckl3s** [thelinmichael/spotify-web-api-java#92]
So I was able to get my API object set up and successfully get an access token, but when I make a call to a track's href link (from api.spotify.com) I get the following 401 error:
java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.spotify.com/v1/tracks/7wGoVu4Dady5GV0Sv4UIsx
Opening ...
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
Apparently I need an access token to access it... so how do I use my current access token for it? 
I'm trying to get the audio from the song , and I have a method that gets audio from a URL. Am I correct in assuming that the above api.spotify.com link will get me that audio?

**Comment by Dargmuesli** [comment]
> On 29th May 2017 the `/search` `/tracks` `/albums` `/artists` and `/users` (and related) endpoints started requiring an access token

This is what Spotify Developer News [states](https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/). This project was not updated since, but I will take care of this soon.

**Comment by Dargmuesli** [comment]
See #102. Every request will require an access token in version 2 of this project. I'm working in it!

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
