### ISSUE TITLE
Undocumented Source Code

### ISSUE THREAD

**Issue by Dargmuesli** [thelinmichael/spotify-web-api-java#95]
Almost the complete source code is uncommented. We seriously need to be able to create meaningful Javadoc content. Therefore comments are mandatory!

**Comment by Dargmuesli** [comment]
@c-schuhmann is currently working on this!

**Comment by Dargmuesli** [comment]
I've updated [GetAlbumRequest.java in v2_requests](https://github.com/thelinmichael/spotify-web-api-java/blob/v2_requests/src/main/java/com/wrapper/spotify/requests/data/albums/GetAlbumRequest.java) as a reference for documentation work in general. Please pay attention to
- links (both `@link` and `<a></a>`)
- full coverage
- closeness to [beta.developer.spotify.com](https://beta.developer.spotify.com/documentation/web-api/reference/albums/get-album/)
- 120 characters per line limit

**Comment by Dargmuesli** [comment]
Mr. Thelin enabled the GitHub Pages feature for this repository under [thelinmichael.github.io/spotify-web-api-java](https://thelinmichael.github.io/spotify-web-api-java). Currently this points to a placeholder and will point to the Javadoc when branch v2 becomes master.

**Comment by Dargmuesli** [comment]
Version 2 of this project is almost complete. I'm working on the final touch-ups.
@c-schuhmann, how long do you think it'll take you to complete your work on the documentation? I'd like to wait for it to be finished before releasing v2. If you need any help, I'm here.

**Comment by c-schuhmann** [comment]
I think I should be finished in a few days but I think it won't take much time because the request endpoints are well documented on the Web API Reference.

**Comment by Dargmuesli** [comment]
Completed in #122. Thanks once more for your great work!
To everyone: Of course the Javadoc can still change. If you find something missing or wrong, just add/correct it.
