### ISSUE TITLE
java.lang.ClassNotFoundException: net.sf.json.JSON

### ISSUE THREAD

**Issue by Tharkius** [thelinmichael/spotify-web-api-java#96]
Lately I've been trying to use this lib in my JavaFX project and I still can't get it to work. I'm using IDEA 2017.2.6, and these are the basic steps to reproduce my problem:

- Create a new JavaFX project
- Create a new Gradle module
- Add this line to the dependencies in build.gradle (I've also tried that workaround for Android Studio 1.0 users):
    compile('se.michaelthelin.spotify:spotify-web-api-java:1.5.0')
- Add this line anywere on the start method of the Main class;
   Api spotifyApi = Api.DEFAULT_API;
- Run the project

And right after running, the app crashes giving the exception in the title, at the spotifyApi line.
Anyone got an idea of what I'm missing here?

**Comment by Dargmuesli** [comment]
https://stackoverflow.com/a/27694582/4682621

**Comment by Dargmuesli** [comment]
Sorry, pressed the wrong button.

Check the solution I linked above. Does this help?

**Comment by Tharkius** [comment]
I tried "apply plugin: 'idea'" to my gradle file and it's still not working.
Where am I supposed to run "gradle idea" from? I'm using the gradle wrapper. I tried running "gradlew idea", since I only have that script, but it also didn't work.

I can't understand how this doesn't work. I mean, all I'm doing is adding a dependency to a blank project ¯\_(ツ)_/¯

**Comment by Tharkius** [comment]
Just tried using a Maven module instead, and still getting the same error. This is my pom:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>test</groupId>
    <artifactId>TestMaven</artifactId>
    <version>1.0</version>

    <dependencies>
        <dependency>
            <groupId>se.michaelthelin.spotify</groupId>
            <artifactId>spotify-web-api-java</artifactId>
            <version>1.5.0</version>
        </dependency>
    </dependencies>
</project>
```

**Comment by Dargmuesli** [comment]
I was able to reproduce your problem with Gradle, but not with Maven.
See if that helps: https://stackoverflow.com/a/5115094/4682621

I will have a closer look at the Gradle error in the next few days.

**Comment by Tharkius** [comment]
Gradle and Maven modules already pull "json-lib" with the "jdk15" classifier, if I add "spotify-web-api-java".

**Comment by Tharkius** [comment]
How were you able to get Maven to work? Because if you found a way to make it work, than Maven it is. Could you share a basic working project?

**Comment by Tharkius** [comment]
Ok, I solved it! Turns out the libraries were missing from my ".iml" file... I knew it had to be something silly xD

I didn't know you have to do this in IDEA, I'm more used to Android Studio, where for some reason, you don't have to...

```
<?xml version="1.0" encoding="UTF-8"?>
<module type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager" inherit-compiler-output="true">
    <exclude-output />
    <content url="file://$MODULE_DIR$">
      <sourceFolder url="file://$MODULE_DIR$/src" isTestSource="false" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
    <orderEntry type="library" name="Gradle: se.michaelthelin.spotify:spotify-web-api-java:1.5.0" level="project" />
    <orderEntry type="library" name="Gradle: net.sf.json-lib:json-lib:jdk15:2.4" level="project" />
    <orderEntry type="library" name="Gradle: commons-httpclient:commons-httpclient:3.1" level="project" />
    <orderEntry type="library" name="Gradle: commons-logging:commons-logging:1.1.1" level="project" />
    <orderEntry type="library" name="Gradle: com.google.protobuf:protobuf-java:2.5.0" level="project" />
  </component>
</module>
```

**Comment by Dargmuesli** [comment]
Ok, glad you were able to sort this out! Maven worked right away, Gradle did not: the mentioned error message appeared. I'm haven't used Gradle before though. Thus I'm not sure what the best way to solve this issue is. Add the entry manually? Edit something within IDEA menus? Setup the project differently? If you have an opinion about this, tell me. I'll consider adding a hint about this to the README.

**Comment by Tharkius** [comment]
You don't have to add the dependencies manually, you can just go to File -> Project Structure -> Press the green plus icon -> Choose "2 Library..." option, and then you'll be presented with a dialog where you can add all the dependencies to the project.

**Comment by Dargmuesli** [comment]
Ok, when I checked, it was listed there, but I think the error appeared nevertheless.
If this keeps being a problem for you or anyone else, please notify me here and I'll add a hint to the README. Thanks for reporting!
