### ISSUE TITLE
Async methods aren't really asyncronous

### ISSUE THREAD

**Issue by Tharkius** [thelinmichael/spotify-web-api-java#98]
How are the getAsync() methods of the various Request classes supposed to be asynchronous, if they don't return until the http request has finished? The "Async" keyword is quite misleading in such methods. 

Wouldn't it be better off to actually make them asynchronous (maybe using ListeningExecutorService)?

**Comment by Dargmuesli** [comment]
Since c15fc2707ba5282d9a2ae8faec5d6149b0e49fa9 asynchonous requests are now correctly bubbling up as Futures to the SpotifyApi class.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
